-- Recovered original generated grammar practice, not an official exam item bank.
-- Source 3a9254ce3905b7d4de430e3d129edf0f62c90962:public/js/generators.js; full recovered bank in content/drills/recovered-grammar.json.
-- Only the coherent twelve-item word-order bank is served. All content remains unreviewed.
-- Answer keys and explanations are stored solely in objective_key; existing worker-only grants apply.
INSERT INTO "__SCHEMA__".content_version (content_version_id,kind,family,source_path,review_status,rights_status,content_sha256,exam_id)
VALUES ('telc-deutsch-b1.sb1.grammar-wortstellung-v1@v1','task','sb','content/drills/recovered-grammar.json#banks.wortstellung_nebensatz','unreviewed','generated','08da25d9af885bf8fc5201ac7a6fcc6bf73eea2dbc8c7335d628138285324208','telc-deutsch-b1');
INSERT INTO "__SCHEMA__".content_rights (content_version_id,basis,decided_by,note)
VALUES ('telc-deutsch-b1.sb1.grammar-wortstellung-v1@v1','generated','Ron (product owner), D1 2026-10-02','AI-generated source recovered under Ron''s 2 October decision. German wording and exam fidelity still await qualified human review.');
INSERT INTO "__SCHEMA__".objective_set (set_id,version,exam_id,family,section,part,title,payload,item_count,media_required,content_version_id)
VALUES ('telc-deutsch-b1.sb1.grammar-wortstellung-v1','v1','telc-deutsch-b1','SB1','SB',1,'Grammatikübung: Wortstellung im Nebensatz','{"practice_kind":"grammar-drill","instruction":"Ergänze die Sätze. Dies sind einzelne Grammatikübungen, kein telc-Prüfungssatz.","letter":"1. Ich weiß, dass er morgen nach Berlin ___ .\n2. Sie kommt heute nicht, weil sie ___ .\n3. Ich rufe dich an, wenn ich ___ .\n4. Er sagt, dass er das Buch schon ___ .\n5. Ich habe gehört, dass du ___ .\n6. Obwohl es stark ___ , sind wir spazieren gegangen.\n7. Ich bleibe zu Hause, weil ich sehr ___ .\n8. Weißt du, wann der Zug ___ ?\n9. Ich möchte wissen, ob du ___ .\n10. Sie hat gesagt, dass sie uns später ___ .\n11. Ich habe ihn gefragt, wo er ___ .\n12. Es ist wichtig, dass du pünktlich ___ .","gaps":[{"n":"g_wortstellung_nebensatz_1bwzwum","prompt":"Ich weiß, dass er morgen nach Berlin ___ .","options":{"a":"fährt","b":"er fährt","c":"fahren"}},{"n":"g_wortstellung_nebensatz_1bns8w","prompt":"Sie kommt heute nicht, weil sie ___ .","options":{"a":"ist krank","b":"krank sein","c":"krank ist"}},{"n":"g_wortstellung_nebensatz_e9k8r3","prompt":"Ich rufe dich an, wenn ich ___ .","options":{"a":"Zeit haben","b":"Zeit habe","c":"habe Zeit"}},{"n":"g_wortstellung_nebensatz_ioh2c5","prompt":"Er sagt, dass er das Buch schon ___ .","options":{"a":"gelesen hat","b":"hat gelesen","c":"gelesen haben"}},{"n":"g_wortstellung_nebensatz_otwf6u","prompt":"Ich habe gehört, dass du ___ .","options":{"a":"bist umgezogen","b":"umgezogen sein","c":"umgezogen bist"}},{"n":"g_wortstellung_nebensatz_1r4f1ml","prompt":"Obwohl es stark ___ , sind wir spazieren gegangen.","options":{"a":"regnen hat","b":"geregnet hat","c":"hat geregnet"}},{"n":"g_wortstellung_nebensatz_ivslwl","prompt":"Ich bleibe zu Hause, weil ich sehr ___ .","options":{"a":"müde bin","b":"bin müde","c":"müde sein"}},{"n":"g_wortstellung_nebensatz_wn4ry5","prompt":"Weißt du, wann der Zug ___ ?","options":{"a":"fährt ab","b":"abfahren","c":"abfährt"}},{"n":"g_wortstellung_nebensatz_i65oho","prompt":"Ich möchte wissen, ob du ___ .","options":{"a":"mitkommen","b":"mitkommst","c":"kommst mit"}},{"n":"g_wortstellung_nebensatz_1tp4oj","prompt":"Sie hat gesagt, dass sie uns später ___ .","options":{"a":"anruft","b":"ruft an","c":"anrufen"}},{"n":"g_wortstellung_nebensatz_1xmbg3q","prompt":"Ich habe ihn gefragt, wo er ___ .","options":{"a":"wohnt er","b":"wohnen","c":"wohnt"}},{"n":"g_wortstellung_nebensatz_1649nxw","prompt":"Es ist wichtig, dass du pünktlich ___ .","options":{"a":"kommen","b":"kommst","c":"kommst du"}}]}'::jsonb,12,false,'telc-deutsch-b1.sb1.grammar-wortstellung-v1@v1');
INSERT INTO "__SCHEMA__".objective_key (set_id,version,answers,explanations,transcript)
VALUES ('telc-deutsch-b1.sb1.grammar-wortstellung-v1','v1','{"g_wortstellung_nebensatz_1bwzwum":"a","g_wortstellung_nebensatz_1bns8w":"c","g_wortstellung_nebensatz_e9k8r3":"b","g_wortstellung_nebensatz_ioh2c5":"a","g_wortstellung_nebensatz_otwf6u":"c","g_wortstellung_nebensatz_1r4f1ml":"b","g_wortstellung_nebensatz_ivslwl":"a","g_wortstellung_nebensatz_wn4ry5":"c","g_wortstellung_nebensatz_i65oho":"b","g_wortstellung_nebensatz_1tp4oj":"a","g_wortstellung_nebensatz_1xmbg3q":"c","g_wortstellung_nebensatz_1649nxw":"b"}'::jsonb,'{"g_wortstellung_nebensatz_1bwzwum":"Im Nebensatz steht das konjugierte Verb am Ende: … dass er morgen nach Berlin fährt.","g_wortstellung_nebensatz_1bns8w":"Nach \"weil\" steht das Verb am Satzende.","g_wortstellung_nebensatz_e9k8r3":"Nebensatz mit \"wenn\" → Verb am Ende.","g_wortstellung_nebensatz_ioh2c5":"Im Nebensatz steht das Hilfsverb nach dem Partizip am Ende.","g_wortstellung_nebensatz_otwf6u":"Perfekt im Nebensatz: Partizip + Hilfsverb am Ende.","g_wortstellung_nebensatz_1r4f1ml":"Nach \"obwohl\" steht das Verb am Ende.","g_wortstellung_nebensatz_ivslwl":"Verb am Ende im \"weil\"-Satz.","g_wortstellung_nebensatz_wn4ry5":"Indirekte Frage: trennbares Verb bleibt zusammen am Ende.","g_wortstellung_nebensatz_i65oho":"Nach \"ob\" steht das Verb am Ende – trennbares Verb zusammen.","g_wortstellung_nebensatz_1tp4oj":"Im Nebensatz bleibt das trennbare Verb am Ende zusammen.","g_wortstellung_nebensatz_1xmbg3q":"Indirekte Frage: Verb am Ende.","g_wortstellung_nebensatz_1649nxw":"\"dass\"-Satz → konjugiertes Verb am Ende."}'::jsonb,NULL);
