
    -- POOL-01 (MIRROR-B1PREP-01, task-37) — batch 1 of the prioritised top-up, GENERATED from
    -- content/pool-01/batch-1.json.
    --
    -- DO NOT EDIT THIS FILE BY HAND. Run:
    --   node tools/build-objective-migration.mjs --batch content/pool-01/batch-1.json --out <this file>
    -- and `--check` fails if this file and the source disagree.
    --
    -- Source: content/pool-01/batch-1.json (sha256 45e361a1c67341d831f78c50a5bcb12a8013a6353566ed1b37abc1b88b319161)
    -- Batch: POOL-01-B1 — authored for Hatoove, every set 'unreviewed'.
    
    
    
    -- CONTENT DECISIONS CONFIRMED (the product owner, relayed by the Lead):
    --   telc-deutsch-b1.lv1.06: item 4 -> headline e; headline e is reworded to "Umzugshilfe: zwei Helfer mit Transporter" (was "Umzugshilfe mit Transporter zu vermieten")
    --   telc-deutsch-b1.lv1.06: item 5 -> headline g
    --
    -- WHY A SECOND MIGRATION AND NOT AN EDIT OF 0010. 0010 is applied in every installation and its bytes
    -- are pinned in MANIFEST.json; a batch is a FORWARD change. This file inserts only its own rows and
    -- nothing else, so applying it to a database that already carries 0010 (or to an empty one) is the
    -- same operation.
    
    -- HELD, and deliberately NOT inserted: telc-deutsch-b1.hv1.04 (HV1), telc-deutsch-b1.hv2.04 (HV2), telc-deutsch-b1.hv3.04 (HV3).
    -- Their scripts and items are authored and validated (tools/pool-01-check.mjs normalises every one of
    -- them), but a listening set whose audio cannot play must not enter the pool, so they wait for the media
    -- bind-mount fix (task-36). Releasing one is a one-word edit to its `release` marker in the source plus a
    -- new forward migration from this same command.
    INSERT INTO "__SCHEMA__".content_version
      (content_version_id, kind, family, source_path, review_status, rights_status, content_sha256, exam_id)
    VALUES
    ('telc-deutsch-b1.lv1.04@v1', 'task', 'lv', 'content/pool-01/batch-1.json#LV1[0]', 'unreviewed', 'unknown', '7c666b41d828e76dbfb6bb6412b8eb2ba7c8a960384be7abd7f04ffed2e99913', 'telc-deutsch-b1'),
    ('telc-deutsch-b1.lv1.05@v1', 'task', 'lv', 'content/pool-01/batch-1.json#LV1[1]', 'unreviewed', 'unknown', 'ed4d6e15530557d5f0b81525d7e9589d202b594899cbc570a54af783a85576f9', 'telc-deutsch-b1'),
    ('telc-deutsch-b1.lv1.06@v1', 'task', 'lv', 'content/pool-01/batch-1.json#LV1[2]', 'unreviewed', 'unknown', '8b6044c9befdd8db84dc3428d724c3943f235a593ddfe31d9b84b353f8f6b971', 'telc-deutsch-b1')
    ON CONFLICT (content_version_id) DO NOTHING;

    -- The rights decision that goes WITH the row. Without it the serving policy fails closed ('unknown' can
    -- never be opted in) and the set would sit in the catalogue, invisible: 0020 records one decision per
    -- content version, and tools/content-rights-check.mjs asserts the invariant.
    INSERT INTO "__SCHEMA__".content_rights (content_version_id, basis, decided_by, note)
    VALUES
    ('telc-deutsch-b1.lv1.04@v1', 'generated', 'Ron (product owner); standing D1 basis applied by POOL-01 task-37', 'Original content authored for Hatoove (no third-party item bank, no published material reproduced); POOL-01 batch 1, task-37, 5 October 2026. Source: content/pool-01/batch-1.json#LV1[0].'),
    ('telc-deutsch-b1.lv1.05@v1', 'generated', 'Ron (product owner); standing D1 basis applied by POOL-01 task-37', 'Original content authored for Hatoove (no third-party item bank, no published material reproduced); POOL-01 batch 1, task-37, 5 October 2026. Source: content/pool-01/batch-1.json#LV1[1].'),
    ('telc-deutsch-b1.lv1.06@v1', 'generated', 'Ron (product owner); standing D1 basis applied by POOL-01 task-37', 'Original content authored for Hatoove (no third-party item bank, no published material reproduced); POOL-01 batch 1, task-37, 5 October 2026. Source: content/pool-01/batch-1.json#LV1[2].')
    ON CONFLICT (content_version_id) DO NOTHING;

    INSERT INTO "__SCHEMA__".objective_set
      (set_id, version, exam_id, family, section, part, title, payload, item_count, media_required, content_version_id)
    VALUES
    ('telc-deutsch-b1.lv1.04', 'v1', 'telc-deutsch-b1', 'LV1', 'LV', 1, 'Second-Hand, Tausch und Reparatur', '{"title":"Second-Hand, Tausch und Reparatur","headlines":[{"id":"a","text":"Kleidung und Bücher für den guten Zweck gesucht"},{"id":"b","text":"Reparaturcafé sucht Helfer mit eigenem Werkzeug"},{"id":"c","text":"Fahrradwerkstatt bietet günstige Inspektionen an"},{"id":"d","text":"Tauschbörse für Kinderkleidung und Spielsachen"},{"id":"e","text":"Möbelhaus verkauft Ausstellungsstücke mit Rabatt"},{"id":"f","text":"Haushaltsgeräte zu verschenken, nur Selbstabholung"},{"id":"g","text":"Werkzeug für Gartenarbeiten am Wochenende ausleihen"},{"id":"h","text":"Flohmarkt für Antiquitäten und alte Bücher"},{"id":"i","text":"Nähkurs für Anfängerinnen und Anfänger"},{"id":"j","text":"Sperrmüll nur nach telefonischer Anmeldung"}],"texts":[{"id":"1","text":"Unser Reparaturcafé öffnet wieder am Samstag von zehn bis vierzehn Uhr. Wir suchen noch Freiwillige, die sich mit Elektrik oder Nähmaschinen auskennen und ihr eigenes Werkzeug mitbringen können."},{"id":"2","text":"Wir ziehen um und geben unsere gut erhaltene Waschmaschine, einen Kühlschrank und zwei Stehlampen kostenlos ab. Die Geräte können am Wochenende abgeholt werden, einen Transport müssen Sie selbst organisieren."},{"id":"3","text":"Am Sonntag treffen sich Familien auf dem Schulhof, um gut erhaltene Kinderkleidung und Spielsachen zu tauschen. Geld wird nicht verwendet, jede Familie bringt einfach mit, was zu Hause übrig ist."},{"id":"4","text":"Für unseren Benefizverkauf im Advent nehmen wir gut erhaltene Kleidung, Bücher und Geschirr entgegen. Der Erlös geht vollständig an eine Einrichtung für Obdachlose in der Stadt."},{"id":"5","text":"Wer im Frühjahr den Garten umgraben oder Hecken schneiden möchte, kann bei uns kostenlos eine Heckenschere, einen Spaten und eine Schubkarre ausleihen. Die Ausgabe ist samstags von neun bis zwölf Uhr geöffnet."}]}'::jsonb, 5, false, 'telc-deutsch-b1.lv1.04@v1'),
    ('telc-deutsch-b1.lv1.05', 'v1', 'telc-deutsch-b1', 'LV1', 'LV', 1, 'Vereine, Feste und Engagement', '{"title":"Vereine, Feste und Engagement","headlines":[{"id":"a","text":"Sportverein sucht Betreuer für die Jugendmannschaft"},{"id":"b","text":"Stadtteilfest: Helfer für Aufbau und Kuchenbuffet"},{"id":"c","text":"Chorprobe für Neueinsteiger ohne Vorkenntnisse"},{"id":"d","text":"Freiwilligenagentur vermittelt Ehrenamt für wenige Stunden"},{"id":"e","text":"Jugendgruppe plant Ausflug in den Freizeitpark"},{"id":"f","text":"Musikschule bietet Schnupperstunden für Gitarre an"},{"id":"g","text":"Kleiderkammer nimmt warme Winterjacken an"},{"id":"h","text":"Nachbarschaftstreff sucht Fahrdienst am Mittwoch"},{"id":"i","text":"Fotoclub stellt Bilder im Rathaus aus"},{"id":"j","text":"Schwimmkurs für Erwachsene am frühen Abend"}],"texts":[{"id":"1","text":"Unser Nachbarschaftstreff organisiert jeden Mittwoch Fahrten zum Arzt und zum Einkaufszentrum. Dafür suchen wir jemanden mit Führerschein und eigenem Auto, der zwei Stunden Zeit hat."},{"id":"2","text":"Für das Stadtteilfest am letzten Augustwochenende brauchen wir noch Unterstützung: Wir suchen Helfer, die beim Aufbau der Bühne helfen und am Nachmittag den Kuchenstand betreuen."},{"id":"3","text":"Unsere Jugendmannschaft trainiert zweimal pro Woche. Weil unser Trainer im Herbst aufhört, suchen wir eine zuverlässige Person, die die Gruppe der Zwölf- bis Fünfzehnjährigen übernehmen möchte."},{"id":"4","text":"Sie singen gern, haben aber noch nie in einem Chor gesungen? Dann kommen Sie einfach am Dienstagabend vorbei. Notenkenntnisse sind nicht nötig, wir lernen die Stimmen gemeinsam."},{"id":"5","text":"Sie möchten sich engagieren, haben aber nur wenige Stunden in der Woche Zeit? Wir vermitteln Aufgaben in der Nachbarschaftshilfe, im Tierheim oder in der Bibliothek – ganz nach Ihren Möglichkeiten."}]}'::jsonb, 5, false, 'telc-deutsch-b1.lv1.05@v1'),
    ('telc-deutsch-b1.lv1.06', 'v1', 'telc-deutsch-b1', 'LV1', 'LV', 1, 'Betreuung, Nachhilfe und Alltagshilfe', '{"title":"Betreuung, Nachhilfe und Alltagshilfe","headlines":[{"id":"a","text":"Nachhilfe in Mathematik für die Klassen 7 bis 10"},{"id":"b","text":"Tagesmutter hat ab September wieder Plätze frei"},{"id":"c","text":"Seniorenbegleitung für Spaziergänge und Gespräche"},{"id":"d","text":"Hundebetreuung am Wochenende"},{"id":"e","text":"Umzugshilfe: zwei Helfer mit Transporter"},{"id":"f","text":"Putzhilfe für Büros am Abend gesucht"},{"id":"g","text":"Erfahrene Babysitterin für zwei Kleinkinder"},{"id":"h","text":"Gitarrenunterricht für Anfänger"},{"id":"i","text":"Sprachkurs Deutsch für den Beruf"},{"id":"j","text":"Möbelmontage und kleine Reparaturen"}],"texts":[{"id":"1","text":"Mein Sohn besucht die neunte Klasse und hat große Schwierigkeiten in Mathematik. Wir suchen eine ruhige Person, die ihm zweimal pro Woche die Aufgaben erklärt und mit ihm für die Klassenarbeiten übt."},{"id":"2","text":"Meine Mutter ist 82 Jahre alt und geht gern spazieren, traut sich aber allein nicht mehr auf die Straße. Wir suchen jemanden, der zweimal in der Woche mit ihr eine Stunde unterwegs ist und sich danach noch etwas zu ihr setzt."},{"id":"3","text":"Wir fahren über das Wochenende zu einer Hochzeit und können unseren freundlichen Labrador nicht mitnehmen. Wer hat Zeit und Lust, mit ihm spazieren zu gehen und ihn zu füttern?"},{"id":"4","text":"Wir ziehen Ende des Monats in eine andere Wohnung. Wer hat einen Transporter und kann uns am Umzugstag für ein paar Stunden helfen? Die Bezahlung sprechen wir vorher ab."},{"id":"5","text":"Wir suchen für unsere beiden Kinder von zwei und vier Jahren eine Betreuerin, die schon Erfahrung mit Kleinkindern hat. Wir brauchen sie montags und donnerstags von sieben bis sechzehn Uhr."}]}'::jsonb, 5, false, 'telc-deutsch-b1.lv1.06@v1')
    ON CONFLICT (set_id, version) DO NOTHING;

    INSERT INTO "__SCHEMA__".objective_key
      (set_id, version, answers, explanations, transcript)
    VALUES
    ('telc-deutsch-b1.lv1.04', 'v1', '{"1":"b","2":"f","3":"d","4":"a","5":"g"}'::jsonb, '{"_set_why":{"1":"Text 1 sucht Freiwillige für ein Reparaturcafé und verlangt ausdrücklich eigenes Werkzeug – das ist Überschrift b.","2":"Text 2 verschenkt Waschmaschine, Kühlschrank und Lampen und verlangt Selbstabholung – das ist Überschrift f.","3":"Text 3 beschreibt eine Tauschbörse für Kinderkleidung und Spielsachen ohne Geld – das ist Überschrift d.","4":"Text 4 sammelt Kleidung und Bücher für einen Benefizverkauf, der Erlös geht an Obdachlose – das ist Überschrift a.","5":"Text 5 verleiht Werkzeug für Gartenarbeiten am Samstag – das ist Überschrift g."}}'::jsonb, NULL),
    ('telc-deutsch-b1.lv1.05', 'v1', '{"1":"h","2":"b","3":"a","4":"c","5":"d"}'::jsonb, '{"_set_why":{"1":"Text 1 sucht für Mittwoch eine Fahrgelegenheit mit eigenem Auto – das ist Überschrift h.","2":"Text 2 sucht Helfer für Aufbau und Kuchenbuffet beim Stadtteilfest – das ist Überschrift b.","3":"Text 3 sucht eine Betreuung für die Jugendmannschaft – das ist Überschrift a.","4":"Text 4 lädt ohne Vorkenntnisse zur Chorprobe ein – das ist Überschrift c.","5":"Text 5 vermittelt Ehrenamt für wenige Stunden pro Woche – das ist Überschrift d."}}'::jsonb, NULL),
    ('telc-deutsch-b1.lv1.06', 'v1', '{"1":"a","2":"c","3":"d","4":"e","5":"g"}'::jsonb, '{"_set_why":{"1":"Text 1 sucht Nachhilfe in Mathematik für die neunte Klasse – das ist Überschrift a.","2":"Text 2 sucht jemanden, der mit einer 82-Jährigen spazieren geht – das ist Überschrift c.","3":"Text 3 sucht Betreuung für einen Hund am Wochenende – das ist Überschrift d.","4":"Text 4 sucht einen Transporter und Hilfe am Umzugstag – das ist Überschrift e.","5":"Text 5 sucht eine erfahrene Betreuerin für zwei Kleinkinder – das ist Überschrift g."}}'::jsonb, NULL)
    ON CONFLICT (set_id, version) DO NOTHING;
