/**
 * Live DeepSeek validation for B1 Prep.
 *
 * Everything AI-facing was previously verified only against tools/mock-deepseek.js,
 * which returns payloads we wrote ourselves. This drives the REAL model through the
 * real UI and reports, per subtest:
 *
 *   - did generation actually come from the model, or did it silently fall back?
 *   - if it fell back, what validation error caused it? (the app surfaces the reason)
 *   - how long did each call take?
 *   - did the writing and speaking graders return a rubric?
 *
 * Run it AFTER saving a real key in Einstellungen. It spends real credit.
 *
 * Usage: node tools/ai-live.js [baseUrl]
 */

import { findBrowser, launchBrowser, connectToPage, makeRecorder, sleep } from './cdp.js';

const BASE = process.argv[2] || 'http://127.0.0.1:4321';
const PORT = 9226;
const PER_CALL_TIMEOUT = 180000;

const PARTS = ['LV1', 'LV2', 'LV3', 'SB1', 'SB2', 'HV1', 'HV2', 'HV3'];

const { record, summary } = makeRecorder();

/** Snapshot what the part view is showing after generation settles. */
const PART_STATE = `
  const view = document.getElementById('view');
  const header = view?.querySelector('.card')?.innerText || '';
  const note = view?.querySelector('.feedback.no')?.innerText || '';
  const error = view?.innerText || '';
  return {
    ai: header.includes('KI-generiert'),
    seed: header.includes('Aufgabensammlung'),
    note: note.replace(/\\s+/g, ' ').trim().slice(0, 240),
    hardFail: error.includes('konnte nicht erstellt werden'),
    bodyChars: (document.querySelector('#part-body')?.innerText || '').length,
    umlauts: /[äöüßÄÖÜ]/.test(document.querySelector('#part-body')?.innerText || ''),
  };
`;

async function checkPart(cdp, partId, label) {
  await cdp.click('[data-view="paper"]');
  await cdp.waitFor(`document.querySelectorAll('[data-part]').length >= 8`, 20000, 'paper index');
  const t0 = Date.now();
  await cdp.click(`[data-part="${partId}"]`);

  let settled = true;
  try {
    await cdp.waitFor(
      `(document.querySelector('#part-body')?.children.length || 0) > 0 || !!document.querySelector('#view .feedback.no')`,
      PER_CALL_TIMEOUT,
      `${partId} to generate`
    );
  } catch {
    settled = false;
  }
  const ms = Date.now() - t0;
  const st = await cdp.evaluate(PART_STATE).catch(() => ({}));

  const ok = settled && !st.hardFail && st.ai && st.bodyChars > 200;
  record(
    `${partId} (${label}) generated by the model`,
    ok,
    `${(ms / 1000).toFixed(1)}s | ai=${st.ai} seed=${st.seed} chars=${st.bodyChars} umlauts=${st.umlauts}` +
      (st.note ? ` | note: ${st.note}` : '')
  );
  if (st.ai && !st.umlauts) record(`${partId} contains German umlauts`, false, 'looks like non-German output');
  return { partId, ms, ...st };
}

async function main() {
  if (!findBrowser()) {
    console.error('No Chrome/Edge found.');
    process.exit(2);
  }

  const cfg = await fetch(`${BASE}/api/config`).then((r) => r.json()).catch(() => null);
  if (!cfg) {
    console.error(`Server not reachable at ${BASE}. Start it with "npm start".`);
    process.exit(2);
  }
  if (!cfg.configured) {
    console.error('\nNo API key is configured, so there is nothing live to test.');
    console.error('Open the app → Einstellungen → paste your DeepSeek key → Speichern → Verbindung testen.');
    process.exit(2);
  }

  console.log('\n=== LIVE DeepSeek validation ===');
  console.log(`Endpoint : ${cfg.baseUrl}`);
  console.log(`Model    : ${cfg.model}`);
  console.log(`Key      : ${cfg.keyMasked}`);
  console.log('\nThis makes real API calls and spends real credit.\n');

  const { cleanup } = await launchBrowser(PORT, { headless: true });
  let cdp = null;
  const timings = [];
  try {
    cdp = await connectToPage(PORT);
    await cdp.send('Page.navigate', { url: BASE });
    await cdp.waitFor(`!!document.querySelector('#view .card')`, 20000, 'app to load');

    const banner = await cdp.evaluate(`return document.body.innerText.includes('Offline-Modus')`);
    record('the app sees the key (no offline banner)', banner === false);

    console.log('\n--- paper parts (one real generation each) ---');
    for (const partId of PARTS) {
      timings.push(await checkPart(cdp, partId, partId.startsWith('LV') ? 'Lesen' : partId.startsWith('SB') ? 'Sprachbausteine' : 'Hören'));
    }

    console.log('\n--- adaptive drill (AI card upgrade) ---');
    await cdp.click('[data-view="drill"]');
    await cdp.waitFor(`!!document.querySelector('.drill-prompt')`, 20000, 'drill');
    await cdp.click('#options .option');
    await cdp.waitFor(`!!document.querySelector('[data-next]')`, 15000, 'feedback');
    await cdp.click('[data-next]');
    let drillAI = false;
    try {
      await cdp.waitFor(`document.body.innerText.includes('KI-generiert')`, 30000, 'AI drill card');
      drillAI = true;
    } catch {
      drillAI = false;
    }
    record('the drill upgrades a card with a real model question', drillAI === true);

    console.log('\n--- writing correction ---');
    await cdp.click('[data-view="writing"]');
    await cdp.waitFor(`!!document.querySelector('#writing-text')`, 60000, 'writing task');
    const t1 = Date.now();
    await cdp.evaluate(`
      const t = document.querySelector('#writing-text');
      t.value = 'Sehr geehrte Frau Berger, ich möchte mich herzlich für den Kurs bedanken, weil er mir sehr geholfen hat. Leider konnte ich an den letzten beiden Terminen nicht teilnehmen, denn ich war krank. Deshalb möchte ich Sie fragen, ob ich die Unterlagen noch bekommen könnte. Außerdem würde ich gern wissen, wann der nächste Kurs beginnt. Über eine kurze Antwort würde ich mich sehr freuen. Mit freundlichen Grüßen Sara';
      t.dispatchEvent(new Event('input'));
      return true;
    `);
    await cdp.click('[data-grade]');
    let gradeOk = false;
    let gradeNote = '';
    try {
      await cdp.waitFor(`document.body.innerText.includes('Aufgabenbewältigung')`, PER_CALL_TIMEOUT, 'grading');
      gradeOk = true;
    } catch {
      gradeNote = (await cdp.evaluate(`return (document.querySelector('#w-result')?.innerText || '').replace(/\\s+/g,' ').slice(0,200)`)) || '';
    }
    const gradeMs = Date.now() - t1;
    const gradeText = (await cdp.evaluate(`return document.body.innerText`)) || '';
    record('writing task came from the model', !gradeText.includes('eingebaute Aufgabe'), '');
    record(
      'writing correction returns the telc rubric',
      gradeOk && gradeText.includes('Formale Richtigkeit') && gradeText.includes('/ 45'),
      `${(gradeMs / 1000).toFixed(1)}s${gradeNote ? ` | ${gradeNote}` : ''}`
    );
    record('writing correction lists concrete errors', gradeText.includes('Korrigieren') || gradeText.includes('→'), '');

    console.log('\n--- speaking feedback ---');
    await cdp.click('[data-view="speaking"]');
    await cdp.waitFor(`!!document.querySelector('[data-grade-speak]')`, 60000, 'speaking task');
    const t2 = Date.now();
    await cdp.evaluate(`
      const t = document.querySelector('#spoken-text');
      t.value = 'Ich möchte Ihnen meine Heimatstadt vorstellen. Sie liegt im Süden und hat etwa zweihunderttausend Einwohner. Besonders bekannt ist der alte Marktplatz. Ein Vorteil ist, dass alles gut zu Fuß erreichbar ist. Andererseits gibt es wenig Arbeitsplätze. Zusammenfassend kann man sagen, dass ich gern dort lebe.';
      t.dispatchEvent(new Event('input'));
      return true;
    `);
    await cdp.click('[data-grade-speak]');
    let speakOk = false;
    let speakNote = '';
    try {
      await cdp.waitFor(
        `const s = document.body.innerText.toLowerCase(); return s.includes('so klingt es besser') || s.includes('nächste schritte')`,
        PER_CALL_TIMEOUT,
        'speaking feedback'
      );
      speakOk = true;
    } catch {
      speakNote = (await cdp.evaluate(`return (document.querySelector('#s-result')?.innerText || '').replace(/\\s+/g,' ').slice(0,200)`)) || '';
    }
    record('speaking feedback returns a rubric', speakOk, `${((Date.now() - t2) / 1000).toFixed(1)}s${speakNote ? ` | ${speakNote}` : ''}`);

    console.log('\n--- full mock exam (9 real generations) ---');
    await cdp.click('[data-view="mock"]');
    await cdp.waitFor(`return !!document.querySelector('[data-start-mock]')`, 20000, 'mock intro');
    const t3 = Date.now();
    await cdp.click('[data-start-mock]');
    let mockOk = false;
    try {
      await cdp.waitFor(`document.querySelector('#view h2')?.textContent.includes('Leseverstehen')`, 300000, 'mock block 1');
      mockOk = true;
    } catch {
      mockOk = false;
    }
    const mockMs = Date.now() - t3;
    const mockText = (await cdp.evaluate(`return document.body.innerText`)) || '';
    record(
      'the full mock exam assembles from the model',
      mockOk,
      `${(mockMs / 1000).toFixed(1)}s` + (mockText.includes('konnten nicht erstellt werden') ? ' | some parts failed to generate' : '')
    );

    console.log('\n--- server-side counters ---');
    await cdp.click('[data-view="settings"]');
    await cdp.waitFor(`return !!document.querySelector('#api-key')`, 20000, 'settings');
    const counters = await cdp.evaluate(`
      const t = document.body.innerText;
      const ok = (t.match(/(\\d+) KI-Aufrufe erfolgreich/) || [])[1];
      const bad = (t.match(/(\\d+) fehlgeschlagen/) || [])[1];
      const err = (t.match(/Letzter Fehler: ([^\\n]+)/) || [])[1] || '';
      return { ok: Number(ok || 0), bad: Number(bad || 0), err: err.slice(0, 200) };
    `);
    record('most model calls succeeded', counters.ok > 0 && counters.bad <= Math.max(1, counters.ok * 0.2), `${counters.ok} ok, ${counters.bad} failed`);
    if (counters.err) console.log(`   last recorded error: ${counters.err}`);

    const errors = cdp.consoleErrors();
    record('no console errors during live generation', errors.length === 0, errors.slice(0, 2).join(' | '));
  } catch (err) {
    record('live run completed without a harness error', false, err.message);
  } finally {
    await cleanup();
    if (cdp) {
      try {
        cdp.ws.close();
      } catch {
        /* ignore */
      }
    }
    await sleep(200);
  }

  const done = timings.filter((t) => Number.isFinite(t.ms));
  if (done.length) {
    const avg = done.reduce((s, t) => s + t.ms, 0) / done.length;
    const slowest = done.slice().sort((a, b) => b.ms - a.ms)[0];
    console.log(`\nGeneration time: avg ${(avg / 1000).toFixed(1)}s, slowest ${slowest.partId} at ${(slowest.ms / 1000).toFixed(1)}s`);
  }

  process.exit(summary() ? 1 : 0);
}

main();
