/** Actual saved reads plus separately labelled rendering/transport/speech fixtures. No live provider. */
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {launchBrowser,connectToPage} from './cdp.js';

export async function verifyExplanations({base,email,newcomerEmail,password,fixture,freePort,record,shot,viewport,theme,nav,setInputs,clickSel,overflow,publishAvailable,drainWorker,grantCredits,withdrawWritingRights,snapshot}) {
 const url=new URL(base);if(url.protocol!=='http:'||!['127.0.0.1','localhost'].includes(url.hostname)||!url.port||['4300','55440'].includes(url.port)||!email.endsWith('@example.test'))throw Error('Disposable source fixture required');
 const assert=(value,message)=>{if(!value)throw Error(message);};let browser,c,prep,attempt,submission,originalView,run;
 const check=async(name,fn)=>{try{await fn();record(name,true);}catch(error){if(c)await shot(c,'failure-'+name.split(' ')[0]).catch(()=>{});record(name,false,error.stack||error.message);throw error;}};
 const api=(route,method='GET',body)=>c.evaluate(`return (async()=>{const session=await (await fetch('/api/auth/get-session')).json();const r=await fetch(${JSON.stringify(route)},{method:${JSON.stringify(method)},headers:{'content-type':'application/json','X-Hatoove-Account':session.user.id}${body===undefined?'':',body:'+JSON.stringify(JSON.stringify(body))}});return {status:r.status,data:await r.json()};})()`);
 const ready=()=>c.waitFor("document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden && document.querySelector('#preparation-picker').value",20000);
 const page=async hash=>{await nav(c,base+'/app/?explanations='+randomUUID()+hash);await ready();};
 const history=async()=>{await page('#/prep/'+prep.id+'/fortschritt');await c.waitFor(`document.querySelector('[data-attempt="${attempt}"]')`,10000);await clickSel(c,`[data-attempt="${attempt}"]`);await c.waitFor("document.querySelector('#writing-state, .archived-writing')",10000);};
 const layouts=async(label,selector)=>{for(const [width,mode] of [[1440,'light'],[390,'dark'],[320,'light']]){await viewport(c,width,width===1440?900:844,width!==1440);await theme(c,mode);await shot(c,`${label}-${width}-${mode}`,selector);const value=await overflow(c);assert(value.offenderCount===0&&value.scrollWidth<=value.innerWidth+2,'Horizontal overflow '+JSON.stringify(value));}await viewport(c,1440,900,false);await theme(c,'light');};
 const choose=async(language,selector='[data-writing-explanation]')=>{await c.evaluate(`const el=document.querySelector(${JSON.stringify(selector+' [data-explanation-language]')});if(!el)throw Error('Language selector missing');el.value=${JSON.stringify(language)};el.dispatchEvent(new Event('change',{bubbles:true}));return true;`);};
 const loaded=(language,selector='[data-writing-explanation]')=>c.waitFor(`document.querySelector(${JSON.stringify(selector)})?.dataset.displayedLanguage===${JSON.stringify(language)} && !document.querySelector(${JSON.stringify(selector)})?.textContent.includes('wird geladen')`,15000);
 const immutable=()=>JSON.stringify(snapshot());
 try{
  publishAvailable();const browserPort=await freePort();browser=await launchBrowser(browserPort);record('P07 isolated browser handle recorded',true,JSON.stringify({pid:browser.proc.pid,profile:browser.profile,port:browserPort}));c=await connectToPage(browserPort);
  // Exact speech payload proof uses synthetic local voices; this is not device/audio acceptance.
  await c.send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__spoken=[];window.__speechCancels=0;Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(text){this.text=text;}}});Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>['de','en','uk','ar','tr'].map(lang=>({lang:lang+'-XX',localService:true})),speak:u=>{window.__spoken.push({text:u.text,lang:u.lang});u.onstart?.();},cancel:()=>{window.__speechCancels++;},addEventListener(){},removeEventListener(){}}});`});
  await viewport(c,1440,900,false);await theme(c,'light');await nav(c,base+'/signin');await setInputs(c,{'si-email':email,'si-password':password});await clickSel(c,'#si-submit');await c.waitFor("document.querySelector('#boot-choices') && !document.querySelector('#boot-choices').hidden || document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden",20000);if(await c.evaluate("return !document.querySelector('#boot-choices').hidden"))await clickSel(c,'[data-preparation]');await ready();
  prep=(await api('/api/v1/preparations','POST',{examId:'dtz-a2-b1'})).data;assert(prep.id,'Preparation absent');grantCredits(prep.id);
  await check('P07B1 actual default worker saves assessment and all five explanation languages',async()=>{
   const task=fixture.writingTasks[0];const made=await api('/api/v1/attempts','POST',{preparationId:prep.id,taskId:task.taskId,taskVersion:task.version,rubricId:task.rubricId,rubricVersion:task.rubricVersion});assert([200,201].includes(made.status),'Attempt refused');attempt=made.data.id;await history();
   await c.waitFor("document.querySelector('#writing-text') && !document.querySelector('#writing-text').readOnly",10000);
   await setInputs(c,{'writing-text':'Sehr geehrte Damen und Herren, leider kann ich am Montag nicht kommen. Können wir einen neuen Termin vereinbaren? Am Dienstag habe ich Zeit. Bitte antworten Sie mir. Vielen Dank. Mit freundlichen Grüßen'});await clickSel(c,'#writing-submit');await c.waitFor("document.querySelector('#writing-state')?.dataset.submissionId",10000);submission=await c.evaluate("return document.querySelector('#writing-state').dataset.submissionId");drainWorker();await c.waitFor("document.querySelector('.criteria .criterion') && document.querySelector('[data-writing-explanation]')?.dataset.explanationState==='original'",20000);
   const before=immutable();for(const language of ['de','en','uk','ar','tr']){await choose(language);await loaded(language);const result=await api('/api/v1/submissions/'+submission+'?explanationLanguage='+language);assert(result.status===200&&result.data.explanation_view.displayed_language===language,'Stored language absent '+language);assert(result.data.explanation_view.representation.persisted,'Representation not persisted');if(language==='de')originalView=result.data.explanation_view;}
   assert(immutable()===before,'Language reads altered assessment/job/debit/provider counters');assert(snapshot().providerAttempts===0,'External provider attempted');await layouts('p07-writing-translated','[data-writing-explanation]');
  });
  await check('P07B2 Arabic is prose-only and exact displayed stored text is passed to local speech',async()=>{
   await choose('ar');await loaded('ar');assert(await c.evaluate("return document.documentElement.dir!=='rtl' && document.querySelector('[data-writing-explanation]').dir==='ltr' && [...document.querySelectorAll('.explanation-prose')].every(el=>el.dir==='rtl'&&el.lang==='ar') && [...document.querySelectorAll('.evidence')].every(el=>el.lang==='de'&&el.dir==='ltr')"),'RTL escaped prose');
   const text=await c.evaluate("return document.querySelector('[data-writing-explanation] .explanation-prose').textContent");await clickSel(c,'[data-writing-explanation] .read-aloud button');assert(await c.evaluate(`return window.__spoken.at(-1)?.text===${JSON.stringify(text)} && window.__spoken.at(-1)?.lang==='ar-XX'`),'Speech text/language differs');const before=await c.evaluate('return window.__speechCancels');await choose('en');await loaded('en');assert(await c.evaluate('return window.__speechCancels')>before,'Language switch did not stop speech');await choose('ar');await loaded('ar');await layouts('p07-arabic-scoped','[data-writing-explanation]');
  });
  await check('P07B3 held real language reads A-B-A discard stale responses and failed reads preserve confirmed prose',async()=>{
   const before=immutable();await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('/api/v1/submissions/')&&String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);
   await choose('ar');await choose('en');await choose('ar');await c.waitFor('window.__held.length===3',15000);await c.evaluate('window.__held[2]();return true;');await loaded('ar');await c.evaluate('window.__held[0]();window.__held[1]();return true;');await c.evaluate('return new Promise(resolve=>setTimeout(resolve,150))');assert(await c.evaluate("return document.querySelector('[data-writing-explanation]').dataset.displayedLanguage==='ar'"),'Stale language won');
   await c.evaluate(`window.fetch=async(...args)=>{if(String(args[0]).includes('explanationLanguage='))throw new TypeError('Explicit synthetic explanation transport failure');return window.__nativeExplanationFetch(...args);};return true;`);await choose('tr');await c.waitFor("document.querySelector('[data-explanation-retry]')",10000);assert(await c.evaluate("return document.querySelector('[data-writing-explanation]').dataset.displayedLanguage==='ar' && document.querySelector('.explanation-status').textContent.includes('العربية')"),'Failure pretended selected translation visible');await layouts('p07-read-failure-retains-arabic','[data-writing-explanation]');
   assert(await c.evaluate('window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch'),'Native fetch restoration failed');await clickSel(c,'[data-explanation-retry]');await loaded('tr');assert(immutable()===before,'Transport/language retry changed grading facts');
  });
  await check('P07B4 leaving a view during held explanation read cannot restore disposed result prose',async()=>{
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('uk');await c.waitFor('window.__held.length===1',10000);await c.evaluate("location.hash='#/heute';return true;");await c.waitFor("!document.querySelector('#view-heute').hidden",10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch');assert(await c.evaluate("return !document.querySelector('[data-writing-explanation] .explanation-prose')"),'Disposed card repopulated');await history();await loaded('de');
  });
  await check('P07B4P actual preparation switch fences a held explanation read',async()=>{
   const list=(await api('/api/v1/preparations')).data;const other=(Array.isArray(list)?list:list.preparations).find(value=>value.id!==prep.id&&value.state==='active');assert(other,'Second preparation fixture missing');
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('en');await c.waitFor('window.__held.length===1',10000);await c.evaluate(`location.hash='#/prep/${other.id}/heute';return true;`);await c.waitFor(`document.querySelector('#preparation-picker').value===${JSON.stringify(other.id)}`,10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch');assert(await c.evaluate("return !document.querySelector('.explanation-prose')"),'Old preparation prose repopulated');await history();await loaded('de');
  });
  await check('P07B5 standalone answer explanation uses actual returned evidence ID and unknown language stays honest',async()=>{
   await page('#/prep/'+prep.id+'/lesen');await c.waitFor("document.querySelector('[data-open]')",10000);await clickSel(c,'[data-open]');await c.waitFor("document.querySelector('[data-answer]')",10000);await clickSel(c,'[data-answer]');await c.waitFor("document.querySelector('[data-objective-explanation]')?.dataset.explanationState && document.querySelector('[data-objective-explanation]')?.dataset.explanationState!=='loading'",15000);
   const evidence=await c.evaluate("return document.querySelector('[data-objective-explanation]').dataset.objectiveExplanation");assert(/^[0-9a-f-]{36}$/.test(evidence),'Exact evidence UUID missing');const before=immutable();const result=await api('/api/v1/objective-evidence/'+evidence+'/explanation?language=ar');assert(result.status===200,'Owned evidence explanation refused');await choose('ar','[data-objective-explanation]');await c.waitFor("document.querySelector('[data-objective-explanation] select').value==='ar' && !document.querySelector('[data-objective-explanation]').textContent.includes('wird geladen')",15000);
   if(result.data.displayed_language===null)assert(await c.evaluate("return !document.querySelector('[data-objective-explanation] .read-aloud') && document.querySelector('[data-objective-explanation]').textContent.includes('Originalsprache')"),'Unknown language invented speech fallback');assert(immutable()===before,'Objective read changed immutable writing/job/charge facts');await layouts('p07-standalone-evidence','[data-objective-explanation]');
  });
  await check('P07B6 finalised mock rereads saved explanations without remounting grading or editable timing actions',async()=>{
   await page('#/prep/'+prep.id+'/abschnitt');await c.waitFor("document.querySelector('[data-mock-start]')",10000);await clickSel(c,'[data-mock-start]');await c.waitFor("document.querySelector('[data-mock-action=confirm]')",10000);run=await c.evaluate("return location.hash.split('/').at(-1)");await clickSel(c,'[data-mock-action=confirm]');await clickSel(c,'[data-mock-action=finalise]');await c.waitFor("document.querySelector('#mock-result') && document.querySelector('[data-mock-explanation] select')",20000);
   assert(await c.evaluate("return !document.querySelector('.mock-timing').textContent.includes('Jetzt bearbeiten')"),'Finalised timing invites editing');const before=immutable(),facts=(await api('/api/v1/mock-runs/'+run)).data.result;await choose('ar','[data-mock-explanation="0"]');await c.waitFor("document.querySelector('[data-mock-explanation=\"0\"] select').value==='ar' && !document.querySelector('[data-mock-explanation=\"0\"]').textContent.includes('wird geladen')",20000);const after=(await api('/api/v1/mock-runs/'+run)).data.result;const clean=x=>JSON.stringify({...x,items:x.items.map(({explanation_view,...row})=>row)});assert(clean(after)===clean(facts)&&immutable()===before,'Saved mock facts/charges changed');await layouts('p07-finalised-mock','#mock-result');
  });
  await check('P07B7 archived assessment keeps grades and permits saved language reads',async()=>{
   await page('#/prep/'+prep.id+'/einstellungen');await setInputs(c,{language:'tr'});await clickSel(c,'#save-settings');await c.waitFor("document.querySelector('#settings-state').textContent==='Gespeichert.'",10000);
   const current=(await api('/api/v1/preparations/'+prep.id)).data;assert((await api('/api/v1/preparations/'+prep.id,'PUT',{expectedRevision:current.revision,state:'archived'})).status===200,'Archive refused');await history();await loaded('tr','[data-archived-explanation]');const before=immutable();await choose('uk','[data-archived-explanation]');await loaded('uk','[data-archived-explanation]');assert(immutable()===before,'Archived read changed facts');await layouts('p07-archived-writing','[data-archived-explanation]');
  });
  await check('P07B8 actual account-cookie switch fences in-flight prose and stops speech',async()=>{
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('ar','[data-archived-explanation]');await c.waitFor('window.__held.length===1',10000);await api('/api/auth/sign-out','POST',{});await c.evaluate(`return fetch('/api/auth/sign-in/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:${JSON.stringify(newcomerEmail)},password:${JSON.stringify(password)}})}).then(r=>r.status);`);await c.evaluate(`return import('/app/api.js').then(m=>m.api.session());`);await c.waitFor("document.querySelector('#error').textContent.includes('Konto wurde')",10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return true;');assert(await c.evaluate("return !document.querySelector('.explanation-prose')"),'Old account prose survived');await layouts('p07-account-fenced','#error');
   await api('/api/auth/sign-out','POST',{});await c.evaluate(`return fetch('/api/auth/sign-in/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:${JSON.stringify(email)},password:${JSON.stringify(password)}})}).then(r=>r.status);`);await history();
  });
  await check('P07B9 actual rights withdrawal removes protected assessment and explanation on fresh read',async()=>{
   withdrawWritingRights();await choose('ar','[data-archived-explanation]');await c.waitFor("document.querySelector('[data-archived-explanation]').dataset.explanationState==='blocked'",15000);assert(await c.evaluate("return !document.querySelector('.criteria') && !document.querySelector('.explanation-prose') && document.querySelector('.archived-writing').textContent.length>0"),'Rights block retained protected facts or lost learner text');await layouts('p07-rights-blocked','[data-archived-explanation]');
  });
  await check('P07B10 isolated synthetic status rendering covers absent pending failed and representation refusals',async()=>{
   // A detached product-independent fixture container imports only the actual renderer; no intercepted API facts.
   await c.evaluate(`return (async()=>{const mod=await import('/app/explanations.js');window.__fixtureManager=mod.createExplanationManager({getLanguage:()=> 'ar'});const host=document.createElement('section');host.id='explanation-fixture-only';host.className='card stack';document.querySelector('main').append(host);window.__fixtureHost=host;return true;})()`);
   for(const status of ['missing','pending','failed','blocked','missing-original']){const view=structuredClone(originalView);view.requested_language='ar';view.state='fallback';view.requested_status=status==='missing-original'?'missing':status;view.reason=status==='blocked'?'representation_withdrawn':'translation_unavailable';if(status==='missing-original'){view.state='missing';view.representation=null;view.displayed_language=null;view.reason='original_missing';}
    await c.evaluate(`window.__fixtureManager.dispose();window.__fixtureHost.replaceChildren();const label=document.createElement('h3');label.textContent='Isolierte synthetische Zustandsprobe: ${status}';window.__fixtureHost.append(label);const card=document.createElement('div');window.__fixtureHost.append(card);const value=${JSON.stringify(view)};window.__fixtureManager.mount(card,{view:value,read:async()=>({ok:true,data:value})});return true;`);await layouts('p07-synthetic-'+status,'#explanation-fixture-only');}
   await c.evaluate('window.__fixtureManager.dispose();window.__fixtureHost.remove();return true;');assert(snapshot().providerAttempts===0,'Read probe attempted external provider');
  });
 }finally{
  try{c?.ws.close();}catch{}if(browser){const pid=browser.proc.pid,profile=browser.profile;await browser.cleanup();assert(!fs.existsSync(profile),'Browser profile remains');let alive=false;try{process.kill(pid,0);alive=true;}catch{}assert(!alive,'Browser process remains');record('P07 browser PID and profile cleanup verified',true,JSON.stringify({pid,profile}));}
 }
}
