/** Actual saved reads plus separately labelled rendering/transport/speech fixtures. No live provider. */
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {launchBrowser,connectToPage} from './cdp.js';
import {packageHash,objectiveItems} from '../server/package-contract.mjs';
import {extractObjectiveExplanationSource,validateExplanationRepresentation} from '../server/explanation-contract.mjs';
export const explanationProviderProbeSource = `import fs from 'node:fs';const native=globalThis.fetch;globalThis.__explanationProviderCalls=0;globalThis.fetch=(input,...args)=>{const url=new URL(input instanceof URL?input.href:typeof input==='string'?input:input?.url);if(!['localhost','127.0.0.1','::1'].includes(url.hostname)){globalThis.__explanationProviderCalls++;fs.appendFileSync('/tmp/explanation-provider-count','x');throw Error('Synthetic fixture refuses external provider I/O');}return native(input,...args);};`;

/** One exact synthetic source declaration, never an exam-language or interface-language guess. */
export function explanationReviewFixture(fixture) {
 const sets=fixture?.sets?.filter(set=>set.family==='LV4'&&set.interaction==='single_choice')??[];
 if(fixture?.exam?.id!=='dtz-a2-b1'||sets.length!==1)throw Error('Exact C06 synthetic set required');
 const set=sets[0],item=objectiveItems(set.payload,set.interaction)[0];
 const original=set.explanations?.[item.id]??set.explanations?._set_why?.[item.id];
 if(typeof original!=='string'||!original.trim())throw Error('Exact C06 original required');
 const identity={examId:fixture.exam.id,setId:set.setId,setVersion:set.version,itemId:item.id};
 const source=extractObjectiveExplanationSource({...identity,originalValue:original,originalLanguage:'de'});
 const arabic='هذه صياغة عربية اصطناعية للاختبار التقني فقط.';
 const payload={schema:'explanation-text-v1',blocks:source.originalPayload.blocks.map(block=>({...block,text:arabic}))};
 const representation=validateExplanationRepresentation(source,{language:'ar',version:'c06-browser-ar-v1',source_sha256:source.sourceSha256,
  payload,payload_sha256:packageHash(payload),provenance:{kind:'publisher-authored',source_sha256:source.sourceSha256,producer_version:'c06-browser-fixture-v1'}});
 return {...identity,original,arabic,sourceSha256:source.sourceSha256,originalPayloadSha256:packageHash(source.originalPayload),representation,
  registry:[{...source.identity,original_value_sha256:packageHash(original),language:'de'}]};
}

export async function verifyExplanations({base,email,newcomerEmail,password,fixture,freePort,record,shot,viewport,theme,nav,setInputs,clickSel,overflow,publishAvailable,drainWorker,grantCredits,withdrawWritingRights,snapshot,reviewFixture,reviewExplanation}) {
 const url=new URL(base);if(url.protocol!=='http:'||!['127.0.0.1','localhost'].includes(url.hostname)||!url.port||['4300','55440'].includes(url.port)||!email.endsWith('@example.test'))throw Error('Disposable source fixture required');
 const assert=(value,message)=>{if(!value)throw Error(message);};let browser,c,prep,attempt,submission,originalView,run;
 const check=async(name,fn)=>{try{await fn();record(name,true);}catch(error){if(c)await shot(c,'failure-'+name.split(' ')[0]).catch(()=>{});record(name,false,error.stack||error.message);throw error;}};
 const api=(route,method='GET',body)=>c.evaluate(`return (async()=>{const session=await (await fetch('/api/auth/get-session')).json();const r=await fetch(${JSON.stringify(route)},{method:${JSON.stringify(method)},headers:{'content-type':'application/json','X-Hatoove-Account':session.user.id}${body===undefined?'':',body:'+JSON.stringify(JSON.stringify(body))}});return {status:r.status,data:await r.json()};})()`);
 const ready=()=>c.waitFor("document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden && document.querySelector('#preparation-picker').value",20000);
 const page=async hash=>{await nav(c,base+'/app/?explanations='+randomUUID()+hash);await ready();};
 const history=async()=>{await page('#/prep/'+prep.id+'/fortschritt');await c.waitFor(`document.querySelector('[data-attempt="${attempt}"]')`,10000);await clickSel(c,`[data-attempt="${attempt}"]`);await c.waitFor("document.querySelector('#writing-state, .archived-writing')",10000);};
 const layouts=async(label,selector)=>{for(const [width,mode] of [[1440,'light'],[390,'dark'],[320,'light']]){await viewport(c,width,width===1440?900:844,width!==1440);await theme(c,mode);await shot(c,`${label}-${width}-${mode}`,selector);const value=await overflow(c);assert(value.offenderCount===0&&value.scrollWidth<=value.innerWidth+2,'Horizontal overflow '+JSON.stringify(value));}await viewport(c,1440,900,false);await theme(c,'light');};
 const choose=async(language,selector='[data-writing-explanation]')=>{await c.evaluate(`const el=document.querySelector(${JSON.stringify(selector+' [data-explanation-language]')});if(!el)throw Error('Language selector missing');el.value=${JSON.stringify(language)};el.dispatchEvent(new Event('change',{bubbles:true}));return true;`);};
 const loaded=(language,selector='[data-writing-explanation]')=>c.waitFor(`document.querySelector(${JSON.stringify(selector)})?.dataset.displayedLanguage===${JSON.stringify(language)} && !document.querySelector(${JSON.stringify(selector)})?.textContent.includes('wird geladen')`,15000);
 const immutable=()=>JSON.stringify(snapshot());
 try{
  publishAvailable();const browserPort=await freePort();browser=await launchBrowser(browserPort);record('P07 isolated browser handle recorded',true,JSON.stringify({pid:browser.proc.pid,profile:browser.profile,port:browserPort}));c=await connectToPage(browserPort);
  // Exact speech payload proof uses synthetic local voices; this is not device/audio acceptance.
  await c.send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__spoken=[];window.__speechCancels=0;Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(text){this.text=text;}}});Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>['de','en','uk','ar','tr'].map(lang=>({lang:lang+'-XX',localService:true})),speak:u=>{window.__spoken.push({text:u.text,lang:u.lang});u.onstart?.();},cancel:()=>{window.__speechCancels++;},addEventListener(){},removeEventListener(){}}});`});
  await viewport(c,1440,900,false);await theme(c,'light');await nav(c,base+'/signin');await setInputs(c,{'si-email':email,'si-password':password});await clickSel(c,'#si-submit');await c.waitFor("document.querySelector('#boot-choices') && !document.querySelector('#boot-choices').hidden || document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden",20000);if(await c.evaluate("return !document.querySelector('#boot-choices').hidden"))await clickSel(c,'[data-preparation]');await ready();
  prep=(await api('/api/v1/preparations','POST',{examId:'dtz-a2-b1'})).data;assert(prep.id,'Preparation absent');grantCredits(prep.id);
  await check('P07B1 actual default worker saves assessment and all five explanation languages',async()=>{
   const task=fixture.writingTasks[0];const made=await api('/api/v1/attempts','POST',{preparationId:prep.id,taskId:task.taskId,taskVersion:task.version,rubricId:task.rubricId,rubricVersion:task.rubricVersion});assert([200,201].includes(made.status),'Attempt refused');attempt=made.data.id;await history();
   await c.waitFor("document.querySelector('#writing-text') && !document.querySelector('#writing-text').readOnly",10000);
   await setInputs(c,{'writing-text':'Sehr geehrte Damen und Herren, leider kann ich am Montag nicht kommen. Können wir einen neuen Termin vereinbaren? Am Dienstag habe ich Zeit. Bitte antworten Sie mir. Vielen Dank. Mit freundlichen Grüßen'});await clickSel(c,'#writing-submit');await c.waitFor("document.querySelector('#writing-state')?.dataset.submissionId",10000);submission=await c.evaluate("return document.querySelector('#writing-state').dataset.submissionId");drainWorker();await c.waitFor("document.querySelector('.criteria .criterion') && document.querySelector('[data-writing-explanation]')?.dataset.explanationState==='original'",20000);
   const before=immutable();for(const language of ['de','en','uk','ar','tr']){await choose(language);await loaded(language);const result=await api('/api/v1/submissions/'+submission+'?explanationLanguage='+language);assert(result.status===200&&result.data.explanation_view.displayed_language===language,'Stored language absent '+language);assert(result.data.explanation_view.representation.persisted,'Representation not persisted');if(language==='de')originalView=result.data.explanation_view;}
   assert(immutable()===before,'Language reads altered assessment/job/debit/provider counters');assert(snapshot().providerAttempts===0,'External provider attempted');await layouts('p07-writing-translated','[data-writing-explanation]');
  });
  await check('P07B2 Arabic is prose-only and exact displayed stored text is passed to local speech',async()=>{
   await choose('ar');await loaded('ar');assert(await c.evaluate("return document.documentElement.dir!=='rtl' && document.querySelector('[data-writing-explanation]').dir==='ltr' && [...document.querySelectorAll('.explanation-prose')].every(el=>el.dir==='rtl'&&el.lang==='ar') && [...document.querySelectorAll('.evidence')].every(el=>el.lang==='de'&&el.dir==='ltr')"),'RTL escaped prose');
   const text=await c.evaluate("return document.querySelector('[data-writing-explanation] .explanation-prose').textContent");await clickSel(c,'[data-writing-explanation] .read-aloud button');assert(await c.evaluate(`return window.__spoken.at(-1)?.text===${JSON.stringify(text)} && window.__spoken.at(-1)?.lang==='ar-XX'`),'Speech text/language differs');const before=await c.evaluate('return window.__speechCancels');await choose('en');await loaded('en');assert(await c.evaluate('return window.__speechCancels')>before,'Language switch did not stop speech');await choose('ar');await loaded('ar');await layouts('p07-arabic-scoped','[data-writing-explanation]');
  });
  await check('P07B3 held real language reads A-B-A discard stale responses and failed reads preserve confirmed prose',async()=>{
   const before=immutable();await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('/api/v1/submissions/')&&String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);
   await choose('ar');await choose('en');await choose('ar');await c.waitFor('window.__held.length===3',15000);await c.evaluate('window.__held[2]();return true;');await loaded('ar');await c.evaluate('window.__held[0]();window.__held[1]();return true;');await c.evaluate('return new Promise(resolve=>setTimeout(resolve,150))');assert(await c.evaluate("return document.querySelector('[data-writing-explanation]').dataset.displayedLanguage==='ar'"),'Stale language won');
   await c.evaluate(`window.fetch=async(...args)=>{if(String(args[0]).includes('explanationLanguage='))throw new TypeError('Explicit synthetic explanation transport failure');return window.__nativeExplanationFetch(...args);};return true;`);await choose('tr');await c.waitFor("document.querySelector('[data-explanation-retry]')",10000);assert(await c.evaluate("return document.querySelector('[data-writing-explanation]').dataset.displayedLanguage==='ar' && document.querySelector('.explanation-status').textContent.includes('العربية')"),'Failure pretended selected translation visible');await layouts('p07-read-failure-retains-arabic','[data-writing-explanation]');
   assert(await c.evaluate('window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch'),'Native fetch restoration failed');await clickSel(c,'[data-explanation-retry]');await loaded('tr');assert(immutable()===before,'Transport/language retry changed grading facts');
  });
  await check('P07B4 leaving a view during held explanation read cannot restore disposed result prose',async()=>{
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('uk');await c.waitFor('window.__held.length===1',10000);await c.evaluate("location.hash='#/heute';return true;");await c.waitFor("!document.querySelector('#view-heute').hidden",10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch');assert(await c.evaluate("return !document.querySelector('[data-writing-explanation] .explanation-prose')"),'Disposed card repopulated');await history();await loaded('de');
  });
  await check('P07B4P actual preparation switch fences a held explanation read',async()=>{
   const list=(await api('/api/v1/preparations')).data;const other=(Array.isArray(list)?list:list.preparations).find(value=>value.id!==prep.id&&value.state==='active');assert(other,'Second preparation fixture missing');
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('en');await c.waitFor('window.__held.length===1',10000);await c.evaluate(`location.hash='#/prep/${other.id}/heute';return true;`);await c.waitFor(`document.querySelector('#preparation-picker').value===${JSON.stringify(other.id)}`,10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch');assert(await c.evaluate("return !document.querySelector('.explanation-prose')"),'Old preparation prose repopulated');await history();await loaded('de');
  });
  await check('P07B5 standalone answer explanation uses actual returned evidence ID and unknown language stays honest',async()=>{
   await page('#/prep/'+prep.id+'/lesen');await c.waitFor("document.querySelector('[data-open]')",10000);await clickSel(c,'[data-open]');await c.waitFor("document.querySelector('[data-answer]')",10000);await clickSel(c,'[data-answer]');await c.waitFor("document.querySelector('[data-objective-explanation]')?.dataset.explanationState && document.querySelector('[data-objective-explanation]')?.dataset.explanationState!=='loading'",15000);
   const evidence=await c.evaluate("return document.querySelector('[data-objective-explanation]').dataset.objectiveExplanation");assert(/^[0-9a-f-]{36}$/.test(evidence),'Exact evidence UUID missing');const before=immutable();const result=await api('/api/v1/objective-evidence/'+evidence+'/explanation?language=ar');assert(result.status===200,'Owned evidence explanation refused');await choose('ar','[data-objective-explanation]');await c.waitFor("document.querySelector('[data-objective-explanation] select').value==='ar' && !document.querySelector('[data-objective-explanation]').textContent.includes('wird geladen')",15000);
   if(result.data.displayed_language===null)assert(await c.evaluate("return !document.querySelector('[data-objective-explanation] .read-aloud') && document.querySelector('[data-objective-explanation]').textContent.includes('Originalsprache')"),'Unknown language invented speech fallback');assert(immutable()===before,'Objective read changed immutable writing/job/charge facts');await layouts('p07-standalone-evidence','[data-objective-explanation]');
  });
  await check('P07B5A later answer receipt owns the card when earlier real answer response arrives last',async()=>{
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__answerHolds=[];window.fetch=async(...args)=>{const answer=String(args[0]).endsWith('/answers')&&args[1]?.method==='POST';if(!answer)return window.__nativeExplanationFetch(...args);const row={};window.__answerHolds.push(row);const response=await window.__nativeExplanationFetch(...args);row.data=await response.clone().json();return new Promise(resolve=>row.release=()=>resolve(response));};return true;`);
   await clickSel(c,'[data-item] [data-answer]');await clickSel(c,'[data-item] [data-answer]');await c.waitFor('window.__answerHolds.length===2 && window.__answerHolds.every(x=>x.release)',15000);const latest=await c.evaluate('window.__answerHolds[1].release();return window.__answerHolds[1].data.evidence_id');await c.waitFor(`document.querySelector('[data-objective-explanation]')?.dataset.objectiveExplanation===${JSON.stringify(latest)}`,15000);await c.evaluate('window.__answerHolds[0].release();window.fetch=window.__nativeExplanationFetch;return fetch===window.__nativeExplanationFetch');await c.evaluate('return new Promise(resolve=>setTimeout(resolve,150))');assert(await c.evaluate(`return document.querySelectorAll('[data-objective-explanation]').length===1 && document.querySelector('[data-objective-explanation]').dataset.objectiveExplanation===${JSON.stringify(latest)} && document.querySelector('[data-objective-explanation]').parentElement.matches('[data-item]')`),'Old answer replaced exact evidence/card or invalid paragraph nesting');
  });
  await check('P07B6 finalised mock rereads saved explanations without remounting grading or editable timing actions',async()=>{
   await page('#/prep/'+prep.id+'/abschnitt');await c.waitFor("document.querySelector('[data-mock-start]')",10000);await clickSel(c,'[data-mock-start]');await c.waitFor("document.querySelector('[data-mock-action=confirm]')",10000);run=await c.evaluate("return location.hash.split('/').at(-1)");await clickSel(c,'[data-mock-action=confirm]');await clickSel(c,'[data-mock-action=finalise]');await c.waitFor("document.querySelector('#mock-result') && document.querySelector('[data-mock-explanation] select')",20000);
   assert(await c.evaluate("return !document.querySelector('.mock-timing').textContent.includes('Jetzt bearbeiten')"),'Finalised timing invites editing');const before=immutable(),facts=(await api('/api/v1/mock-runs/'+run)).data.result;await choose('ar','[data-mock-explanation="0"]');await c.waitFor("document.querySelector('[data-mock-explanation=\"0\"] select').value==='ar' && !document.querySelector('[data-mock-explanation=\"0\"]').textContent.includes('wird geladen')",20000);const after=(await api('/api/v1/mock-runs/'+run)).data.result;const clean=x=>JSON.stringify({...x,items:x.items.map(({explanation_view,...row})=>row)});assert(clean(after)===clean(facts)&&immutable()===before,'Saved mock facts/charges changed');await layouts('p07-finalised-mock','#mock-result');
  });
  const reviewedCard=`[data-item="${reviewFixture.itemId}"] [data-objective-explanation]`;
  let reviewedEvidence,reviewFacts,answerFact,mockFacts,reviewedIndex;
  const cleanMock=value=>JSON.stringify({...value,items:value.items.map(({explanation_view,...row})=>row)});
  const reviewRead=async()=>{const response=await api('/api/v1/objective-evidence/'+reviewedEvidence+'/explanation?language=ar');assert(response.status===200,'Exact reviewed evidence refused');return response.data;};
  const assertPrivateFree=value=>assert(!/"(?:decision_ids|target_id|targetId|reviewer_id|authority_id|packet_sha256|reviewSourceBinding|review_source_binding|sourceOrigin)"/.test(JSON.stringify(value)),'Private review metadata entered learner DTO');
  const assertReview=(view,status)=>{assertPrivateFree(view);assert(['educational','native_language'].every(dimension=>view.review[dimension].review_status===status&&view.review[dimension].review_basis===(status==='approved'?'named_decision':'none')),'Exact review dimensions not '+status);};
  const assertStable=async()=>{assert(immutable()===reviewFacts,'Review/read changed saved facts, charges, provider observations or representation heads');assert(cleanMock((await api('/api/v1/mock-runs/'+run+'?explanationLanguage=ar')).data.result)===mockFacts,'Review changed immutable mock marking');assert(await c.evaluate(`return document.querySelector('[data-item="${reviewFixture.itemId}"] .result')?.textContent===${JSON.stringify(answerFact)}`),'Review changed answer receipt');};
  const holdReviewedRead=()=>c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const response=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes(${JSON.stringify('/objective-evidence/')})&&String(args[0]).includes('language=ar'))return new Promise(resolve=>window.__held.push(()=>resolve(response)));return response;};return true;`);
  const releaseReviewedRead=()=>c.evaluate('if(window.__held.length!==1)throw Error("Expected one held authoritative read");window.__held[0]();window.fetch=window.__nativeExplanationFetch;return true;');
  await check('C06B1 actual registered shared targets remain visibly unreviewed before decisions',async()=>{
   reviewExplanation('register');await page('#/prep/'+prep.id+'/lesen');await c.waitFor(`document.querySelector('[data-open="${reviewFixture.setId}"][data-version="${reviewFixture.setVersion}"]')`,10000);
   await clickSel(c,`[data-open="${reviewFixture.setId}"][data-version="${reviewFixture.setVersion}"]`);await c.waitFor(`document.querySelector('[data-item="${reviewFixture.itemId}"] [data-answer]')`,10000);await clickSel(c,`[data-item="${reviewFixture.itemId}"] [data-answer]`);await loaded('de',reviewedCard);
   reviewedEvidence=await c.evaluate(`return document.querySelector(${JSON.stringify(reviewedCard)}).dataset.objectiveExplanation`);assert(/^[0-9a-f-]{36}$/.test(reviewedEvidence),'Review fixture lacks actual answer evidence');
   await choose('ar',reviewedCard);await loaded('ar',reviewedCard);const view=await reviewRead();assertReview(view,'unreviewed');assert(view.representation.persisted&&view.representation.payload.blocks[0].text===reviewFixture.arabic,'Actual imported representation missing');
   assert(await c.evaluate(`return document.querySelector(${JSON.stringify(reviewedCard)}).textContent.includes('Fachliche Prüfung: ausstehend')&&document.querySelector(${JSON.stringify(reviewedCard)}).textContent.includes('Sprachliche Prüfung: ausstehend')`),'Unreviewed labels missing');
   answerFact=await c.evaluate(`return document.querySelector('[data-item="${reviewFixture.itemId}"] .result').textContent`);const result=(await api('/api/v1/mock-runs/'+run+'?explanationLanguage=ar')).data.result;
   reviewedIndex=result.items.findIndex(item=>item.set_id===reviewFixture.setId&&item.version===reviewFixture.setVersion&&item.item_id===reviewFixture.itemId);assert(reviewedIndex>=0,'Exact reviewed item absent from finalised run');mockFacts=cleanMock(result);reviewFacts=immutable();await layouts('c06-registered-unreviewed',reviewedCard);
  });
  await check('C06B2 actual educational and native decisions approve exact Arabic; confirmed locale fences held prose',async()=>{
   reviewExplanation('approve');await choose('ar',reviewedCard);await loaded('ar',reviewedCard);assertReview(await reviewRead(),'approved');
   assert(await c.evaluate(`const host=document.querySelector(${JSON.stringify(reviewedCard)});return host.textContent.includes('Fachliche Prüfung: freigegeben')&&host.textContent.includes('Sprachliche Prüfung: freigegeben')&&host.querySelector('.explanation-prose').lang==='ar'&&host.querySelector('.explanation-prose').dir==='rtl'&&document.querySelector('[data-item="${reviewFixture.itemId}"] [data-answer]').lang==='de'&&document.documentElement.dir!=='rtl';`),'Named review labels or source/Arabic scope wrong');
   await layouts('c06-named-approved-arabic',reviewedCard);
   await holdReviewedRead();await choose('ar',reviewedCard);await c.waitFor('window.__held.length===1',10000);await setInputs(c,{'header-language':'en'});
   await c.waitFor(`document.documentElement.lang==='en'&&document.querySelector(${JSON.stringify(reviewedCard+' select')})?.value==='en'&&document.querySelector(${JSON.stringify(reviewedCard)})?.dataset.displayedLanguage==='de'`,15000);
   await releaseReviewedRead();await c.evaluate('return new Promise(resolve=>setTimeout(resolve,150))');assert(await c.evaluate(`return document.documentElement.lang==='en'&&document.querySelector(${JSON.stringify(reviewedCard+' select')}).value==='en'&&document.querySelector(${JSON.stringify(reviewedCard+' .explanation-prose')}).lang==='de'`),'Late Arabic read overrode confirmed locale');
   await setInputs(c,{'header-language':'de'});await c.waitFor("document.documentElement.lang==='de'",15000);await choose('ar',reviewedCard);await loaded('ar',reviewedCard);await assertStable();
  });
  await check('C06B3 real translation withdrawal removes prior Arabic and speech but retains separately approved German original',async()=>{
   reviewExplanation('withdraw_translation');await holdReviewedRead();await choose('ar',reviewedCard);await c.waitFor('window.__held.length===1',10000);
   // Begin speech after the request's loading render. Only the confirmed response can clear this speech.
   await clickSel(c,reviewedCard+' .read-aloud button');assert(await c.evaluate(`return window.__spoken.at(-1)?.text===${JSON.stringify(reviewFixture.arabic)}&&window.__spoken.at(-1)?.lang==='ar-XX'`),'Prior confirmed Arabic speech not active');const cancellations=await c.evaluate('return window.__speechCancels');
   await releaseReviewedRead();await loaded('de',reviewedCard);const view=await reviewRead();assert(view.state==='fallback'&&view.requested_status==='blocked'&&view.reason==='representation_withdrawn'&&view.displayed_language==='de','Withdrawn translation did not fall back truthfully');assertReview(view,'approved');
   assert(await c.evaluate(`return window.__speechCancels>${cancellations}&&document.querySelector(${JSON.stringify(reviewedCard+' .explanation-prose')}).textContent===${JSON.stringify(reviewFixture.original)}&&document.querySelector(${JSON.stringify(reviewedCard+' .explanation-prose')}).lang==='de'&&document.querySelector(${JSON.stringify(reviewedCard+' .explanation-prose')}).dir==='ltr'&&!document.querySelector(${JSON.stringify(reviewedCard)}).textContent.includes(${JSON.stringify(reviewFixture.arabic)})`),'Withdrawal retained prior prose/speech or mislabeled fallback');await assertStable();await layouts('c06-translation-withdrawn-original-fallback',reviewedCard);
  });
  await check('C06B4 real original withdrawal clears both representations and active speech without changing answer or grades',async()=>{
   reviewExplanation('withdraw_original');await holdReviewedRead();await choose('ar',reviewedCard);await c.waitFor('window.__held.length===1',10000);await clickSel(c,reviewedCard+' .read-aloud button');assert(await c.evaluate(`return window.__spoken.at(-1)?.text===${JSON.stringify(reviewFixture.original)}&&window.__spoken.at(-1)?.lang==='de-XX'`),'Confirmed original speech not active');const cancellations=await c.evaluate('return window.__speechCancels');
   await releaseReviewedRead();await c.waitFor(`document.querySelector(${JSON.stringify(reviewedCard)})?.dataset.explanationState==='blocked'`,15000);const view=await reviewRead();assertPrivateFree(view);assert(view.source?.source_sha256===reviewFixture.sourceSha256&&view.representation===null&&view.state==='blocked'&&view.requested_status==='blocked'&&view.reason==='representation_withdrawn','Both-blocked exact-source DTO wrong');
   assert(await c.evaluate(`return window.__speechCancels>${cancellations}&&!document.querySelector(${JSON.stringify(reviewedCard+' .explanation-prose')})&&!document.querySelector(${JSON.stringify(reviewedCard+' .read-aloud')})`),'Both-blocked view retained prose or speech');await assertStable();await layouts('c06-both-withdrawn',reviewedCard);
  });
  await check('C06B5 actual finalised mock observes same exact negative while saved score and German evidence remain',async()=>{
   await page('#/prep/'+prep.id+'/abschnitt/'+run);const selector=`[data-mock-explanation="${reviewedIndex}"]`;await c.waitFor(`document.querySelector(${JSON.stringify(selector)})?.dataset.explanationState==='blocked'`,15000);
   const after=(await api('/api/v1/mock-runs/'+run+'?explanationLanguage=ar')).data.result;assert(cleanMock(after)===mockFacts&&immutable()===reviewFacts,'Finalised review read changed saved facts');const view=after.items[reviewedIndex].explanation_view;assertPrivateFree(view);assert(view.representation===null&&view.source?.source_sha256===reviewFixture.sourceSha256,'Finalised exact review not enforced');
   assert(await c.evaluate(`return !document.querySelector(${JSON.stringify(selector+' .explanation-prose')})&&!document.querySelector(${JSON.stringify(selector+' .read-aloud')})&&document.querySelector('#mock-result').textContent.length>0`),'Finalised blocked card retained prose or removed result');await layouts('c06-finalised-negative','#mock-result');assert(snapshot().providerAttempts===0,'Review/read attempted an external provider');
  });
  await check('P07B7 archived assessment keeps grades and permits saved language reads',async()=>{
   await page('#/prep/'+prep.id+'/einstellungen');await setInputs(c,{language:'tr'});await clickSel(c,'#save-settings');await c.waitFor("document.documentElement.lang==='tr'&&document.querySelector('#settings-state').textContent==='Kaydedildi.'",10000);
   const current=(await api('/api/v1/preparations/'+prep.id)).data;assert((await api('/api/v1/preparations/'+prep.id,'PUT',{expectedRevision:current.revision,state:'archived'})).status===200,'Archive refused');await history();await loaded('tr','[data-archived-explanation]');const before=immutable();await choose('uk','[data-archived-explanation]');await loaded('uk','[data-archived-explanation]');assert(immutable()===before,'Archived read changed facts');await layouts('p07-archived-writing','[data-archived-explanation]');
   // Retained following copy assertions deliberately use the confirmed German interface.
   await setInputs(c,{'header-language':'de'});await c.waitFor("document.documentElement.lang==='de'",15000);await choose('uk','[data-archived-explanation]');await loaded('uk','[data-archived-explanation]');
  });
  await check('P07B8 actual account-cookie switch fences in-flight prose and stops speech',async()=>{
   await c.evaluate(`window.__nativeExplanationFetch=fetch;window.__held=[];window.fetch=async(...args)=>{const r=await window.__nativeExplanationFetch(...args);if(String(args[0]).includes('explanationLanguage='))return new Promise(resolve=>window.__held.push(()=>resolve(r)));return r;};return true;`);await choose('ar','[data-archived-explanation]');await c.waitFor('window.__held.length===1',10000);await clickSel(c,'[data-archived-explanation] .read-aloud button');assert(await c.evaluate("return window.__spoken.at(-1)?.lang==='uk-XX' && document.querySelector('[data-archived-explanation] .read-aloud button').getAttribute('aria-pressed')==='true'"),'Confirmed-card speech did not start');const cancelBefore=await c.evaluate('return window.__speechCancels');await api('/api/auth/sign-out','POST',{});await c.evaluate(`return fetch('/api/auth/sign-in/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:${JSON.stringify(newcomerEmail)},password:${JSON.stringify(password)}})}).then(r=>r.status);`);await c.evaluate(`return import('/app/api.js').then(m=>m.api.session());`);await c.waitFor("document.querySelector('#error').textContent.includes('Konto wurde')",10000);await c.evaluate('window.__held[0]();window.fetch=window.__nativeExplanationFetch;return true;');assert(await c.evaluate("return !document.querySelector('.explanation-prose')"),'Old account prose survived');assert(await c.evaluate('return window.__speechCancels')>cancelBefore,'Account transition did not cancel speaking confirmed text');await layouts('p07-account-fenced','#error');
   await api('/api/auth/sign-out','POST',{});await c.evaluate(`return fetch('/api/auth/sign-in/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:${JSON.stringify(email)},password:${JSON.stringify(password)}})}).then(r=>r.status);`);await history();
  });
  await check('P07B9 actual rights withdrawal removes protected assessment and explanation on fresh read',async()=>{
   withdrawWritingRights();await choose('ar','[data-archived-explanation]');await c.waitFor("document.querySelector('[data-archived-explanation]').dataset.explanationState==='blocked'",15000);assert(await c.evaluate("return !document.querySelector('.criteria') && !document.querySelector('.explanation-prose') && document.querySelector('.archived-writing').textContent.length>0"),'Rights block retained protected facts or lost learner text');await layouts('p07-rights-blocked','[data-archived-explanation]');
  });
  await check('P07B10 isolated synthetic status rendering covers absent pending failed and representation refusals',async()=>{
   // A detached product-independent fixture container imports only the actual renderer; no intercepted API facts.
   await c.evaluate(`return (async()=>{const mod=await import('/app/explanations.js');window.__fixtureManager=mod.createExplanationManager({getLanguage:()=> 'ar'});const host=document.createElement('section');host.id='explanation-fixture-only';host.className='card stack';document.querySelector('main').append(host);window.__fixtureHost=host;return true;})()`);
   for(const status of ['missing','pending','failed','blocked','rejected','blocked-both','missing-original']){const view=structuredClone(originalView);view.requested_language='ar';view.state='fallback';view.requested_status=['rejected','blocked-both'].includes(status)?'blocked':status==='missing-original'?'missing':status;view.reason=status==='rejected'?'representation_rejected':['blocked','blocked-both'].includes(status)?'representation_withdrawn':'translation_unavailable';if(status==='blocked-both'){view.state='blocked';view.representation=null;view.displayed_language=null;}if(status==='missing-original'){view.state='missing';view.representation=null;view.displayed_language=null;view.reason='original_missing';}
    await c.evaluate(`window.__fixtureManager.dispose();window.__fixtureHost.replaceChildren();const label=document.createElement('h3');label.textContent='Isolierte synthetische Zustandsprobe: ${status}';window.__fixtureHost.append(label);const card=document.createElement('div');window.__fixtureHost.append(card);const value=${JSON.stringify(view)};window.__fixtureManager.mount(card,{view:value,read:async()=>({ok:true,data:value})});return true;`);const rendered=await c.evaluate("const card=window.__fixtureHost.querySelector('.explanation-view');return {state:card?.dataset.explanationState,displayed:card?.dataset.displayedLanguage,selected:card?.querySelector('select')?.value,status:card?.querySelector('.explanation-status')?.textContent,blocks:[...card.querySelectorAll('.explanation-prose')].map(p=>({slot:p.dataset.explanationSlot,text:p.textContent,lang:p.lang,dir:p.dir}))};");
    assert(rendered.state===view.state&&rendered.selected==='ar'&&rendered.displayed===(view.displayed_language||''),'Synthetic state/language projection missing '+status);
    const wording={missing:'noch nicht verfügbar',pending:'wird vorbereitet',failed:'fehlgeschlagen',blocked:'gesperrt',rejected:'gesperrt','blocked-both':'zurzeit gesperrt','missing-original':'keine unterstützte Erklärung'}[status];assert(rendered.status?.includes(wording),'Synthetic status wording absent '+status);
    const expected=(view.representation?.payload.blocks||[]).map(block=>({...block,lang:'de',dir:'ltr'}));assert(JSON.stringify(rendered.blocks)===JSON.stringify(expected),'Synthetic fallback text/language or zero-prose refusal wrong '+status);
    await layouts('p07-synthetic-'+status,'#explanation-fixture-only');}
   await c.evaluate('window.__fixtureManager.dispose();window.__fixtureHost.remove();return true;');assert(snapshot().providerAttempts===0,'Read probe attempted external provider');
  });
 }finally{
  try{c?.ws.close();}catch{}if(browser){const pid=browser.proc.pid,profile=browser.profile;await browser.cleanup();assert(!fs.existsSync(profile),'Browser profile remains');let alive=false;try{process.kill(pid,0);alive=true;}catch{}assert(!alive,'Browser process remains');record('P07 browser PID and profile cleanup verified',true,JSON.stringify({pid,profile}));}
 }
}
