/** Combined locale acceptance against the wrapper's disposable source-only DTZ fixture.
 * Holds/discards real responses only. No fake account, grading or admission acknowledgements.
 */
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {launchBrowser,connectToPage} from './cdp.js';
import {instructionView} from '../public/assets/i18n/instructions.js';

const locales=['de','en','uk','ar','tr'];
const text='Sehr geehrte Damen und Herren, leider kann ich am Montag nicht kommen. Können wir einen neuen Termin vereinbaren? Am Dienstag habe ich Zeit. Bitte antworten Sie mir. Vielen Dank. Mit freundlichen Grüßen';
export async function verifyI18n({base,email,newcomerEmail,password,fixture,freePort,record,shot,viewport,theme,setInputs,clickSel,publishAvailable,grantCredits,drainWorker}) {
  const target=new URL(base);
  if(target.protocol!=='http:'||target.hostname!=='127.0.0.1'||!target.port||['4300','55440'].includes(target.port)||
    ![email,newcomerEmail].every(x=>/^(browser|newcomer)-\d+_\d+@example\.test$/.test(x))||fixture.exam.id!=='dtz-a2-b1'||fixture.release.version!=='v9700')throw Error('Exact disposable locale fixture required');
  const browsers=[],connections=[];let c,peer,prep,attempt,submission,run,gradedFacts;
  const assert=(condition,message)=>{if(!condition)throw Error(message);};
  const check=async(name,fn)=>{try{const detail=await fn();record(name,true,detail||'');}catch(error){if(c)await shot(c,'failure-'+name.split(' ')[0]).catch(()=>{});record(name,false,error.stack||error.message);throw error;}};
  // Assertion reads bypass only this document's explicit transport probe, retaining real cookies/account fence.
  const api=(client,route,method='GET',body)=>client.evaluate(`return (async()=>{const native=window.__localeNative||fetch;const session=await (await native('/api/auth/get-session')).json();const response=await native(${JSON.stringify(route)},{method:${JSON.stringify(method)},headers:{'content-type':'application/json','X-Hatoove-Account':session.user.id}${body===undefined?'':',body:'+JSON.stringify(JSON.stringify(body))}});return {status:response.status,data:await response.json()};})()`);
  const ready=client=>client.waitFor("document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden && document.querySelector('#preparation-picker').value",20000);
  const boot=async client=>{await client.waitFor("document.querySelector('#boot-choices') && !document.querySelector('#boot-choices').hidden || document.querySelector('#app-shell') && !document.querySelector('#app-shell').hidden",20000);if(await client.evaluate("return !document.querySelector('#boot-choices').hidden"))await clickSel(client,'[data-preparation]');await ready(client);};
  // Unique query + old-document marker prevents a previous complete document satisfying the wait.
  const navigate=async(client,url)=>{const marker=randomUUID(),destination=new URL(url);destination.searchParams.set('localeEvidence',marker);await client.evaluate(`window.__localeDocument=${JSON.stringify(marker)};return true;`);const response=await client.send('Page.navigate',{url:destination.href});assert(response.loaderId,'Expected a new document');await client.waitFor(`window.__localeDocument!==${JSON.stringify(marker)} && document.readyState==='complete'`,25000);};
  const page=async(hash,client=c)=>{await navigate(client,base+'/app/'+hash);await ready(client);};
  const launch=async()=>{const port=await freePort(),browser=await launchBrowser(port);browsers.push(browser);const client=await connectToPage(port);connections.push(client);await client.send('Network.enable');await viewport(client,1440,900,false);await theme(client,'light');return client;};
  const signin=async(client,address)=>{await navigate(client,base+'/signin');await setInputs(client,{'si-email':address,'si-password':password});await clickSel(client,'#si-submit');await boot(client);};
  const locale=async(language,client=c)=>{await client.waitFor("document.querySelector('#header-language') && !document.querySelector('#header-language').disabled",12000);await client.evaluate(`const input=document.querySelector('#header-language');input.value=${JSON.stringify(language)};input.dispatchEvent(new Event('change',{bubbles:true}));return true;`);await client.waitFor(`document.documentElement.lang===${JSON.stringify(language)} && !document.querySelector('#header-language').disabled`,12000);const saved=await api(client,'/api/v1/settings');assert(saved.status===200&&saved.data.settings.language===language,'Displayed locale lacks a confirmed server preference');};
  const pointer=async selector=>{const point=await c.evaluate(`const node=document.querySelector(${JSON.stringify(selector)});if(!node||node.disabled)return null;node.scrollIntoView({block:'center'});const r=node.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};`);assert(point,'Unavailable pointer target '+selector);await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});};
  const directions=async language=>{const rows=await c.evaluate("return [...document.querySelectorAll('[data-instruction]')].filter(n=>n.getBoundingClientRect().height).map(n=>({options:JSON.parse(n.dataset.instruction),digest:n.dataset.instructionDigest,original:n.querySelector('[data-instruction-original]').textContent,originalLang:n.querySelector('[data-instruction-original]').lang,originalDir:n.querySelector('[data-instruction-original]').dir,translation:n.querySelector('[data-instruction-translation]').textContent,lang:n.querySelector('[data-instruction-translation]').lang,dir:n.querySelector('[data-instruction-translation]').dir,hidden:n.querySelector('[data-instruction-translation]').hidden}));");assert(rows.length>0,'No visible operational directions');for(const row of rows){const expected=instructionView({...row.options,locale:language});assert(expected.known&&row.digest===expected.digest&&row.original===expected.original&&row.originalLang==='de'&&row.originalDir==='ltr','Original instruction identity changed');assert(row.translation===expected.translation&&row.lang===language&&row.dir===(language==='ar'?'rtl':'ltr')&&row.hidden===(language==='de'),'Selected-language instruction mismatch');}};
  const layout=async(name,selector)=>{for(const [width,mode] of [[1440,'light'],[390,'dark'],[320,'light']]){await viewport(c,width,width===1440?900:844,width!==1440);await theme(c,mode);await shot(c,name+'-'+width+'-'+mode,selector);const result=await c.evaluate("const width=innerWidth;const clipped=e=>{for(let p=e.parentElement;p&&p!==document.documentElement;p=p.parentElement)if(['auto','scroll','hidden','clip'].includes(getComputedStyle(p).overflowX))return true;return false;};return {width,scroll:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.right>width+2||r.left < -2)&&!clipped(e);}).slice(0,6).map(e=>e.tagName+'.'+e.className)};");assert(result.scroll<=result.width+2&&!result.bad.length,'Horizontal overflow '+JSON.stringify(result));}await viewport(c,1440,900,false);await theme(c,'light');};
  const probe=async(path,method,{drop=false}={})=>c.evaluate(`window.__localeNative=fetch;window.__localeRequests=[];window.__localeAllRequests=[];window.__localeHeld=false;window.__localeRelease=null;window.__localeOnce=true;window.fetch=async(input,init)=>{const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url,location.href);const verb=init?.method||input?.method||'GET';window.__localeAllRequests.push({path:url.pathname,method:verb});const tracked=url.pathname===${JSON.stringify(path)}&&verb===${JSON.stringify(method)};const row=tracked?{path:url.pathname,method:verb,body:JSON.parse(init?.body||'{}')}:null;if(row)window.__localeRequests.push(row);const response=await window.__localeNative(input,init);if(row){row.status=response.status;row.data=await response.clone().json();}if(tracked&&window.__localeOnce){window.__localeOnce=false;window.__localeHeld=true;await new Promise(resolve=>{window.__localeRelease=resolve;});${drop?"throw new TypeError('Synthetic lost acknowledgement after actual response');":''}}return response;};return true;`);
  const release=()=>c.evaluate('window.__localeRelease();return true;');
  const restore=()=>c.evaluate('window.fetch=window.__localeNative;delete window.__localeNative;return true;');
  const graded=async()=>{const response=await api(c,'/api/v1/export');assert(response.status===200,'Export unavailable');const data=response.data,keys=['submissions','results','balances','provider_attempts'];for(const key of keys)assert(Array.isArray(data[key]),'Missing exported fact array '+key);assert(data.submissions.some(row=>row.id===submission)&&data.results.some(row=>row.submission_id===submission&&row.status==='succeeded'),'Completed fact controls absent');return JSON.stringify(Object.fromEntries(keys.map(key=>[key,data[key]])));};
  const draft=async()=>{const task=fixture.writingTasks[0],response=await api(c,'/api/v1/attempts','POST',{preparationId:prep.id,taskId:task.taskId,taskVersion:task.version,rubricId:task.rubricId,rubricVersion:task.rubricVersion});assert([200,201].includes(response.status),'Draft not admitted');await page('#/prep/'+prep.id+'/fortschritt');await c.waitFor(`document.querySelector('[data-attempt="${response.data.id}"]')`,10000);await clickSel(c,`[data-attempt="${response.data.id}"]`);await c.waitFor("document.querySelector('#writing-text') && !document.querySelector('#writing-text').readOnly",10000);return response.data;};
  try {
    publishAvailable();c=await launch();await signin(c,email);peer=await launch();await signin(peer,email);
    const created=await api(c,'/api/v1/preparations','POST',{examId:'dtz-a2-b1'});assert([200,201].includes(created.status),'Named synthetic DTZ unavailable');prep=created.data;grantCredits(prep.id);await page('#/prep/'+prep.id+'/heute');
    await check('I18NB1 confirmed account preference wins a conflicting guest scalar',async()=>{await locale('uk');await c.evaluate("localStorage.setItem('hatoove.interface-language.v1','ar');return true;");await page('#/prep/'+prep.id+'/heute');await c.waitFor("document.documentElement.lang==='uk'",10000);assert((await api(c,'/api/v1/settings')).data.settings.language==='uk','Guest scalar overwrote server');});
    await check('I18NB2 lost settings acknowledgement reconciles one real write without blind replay',async()=>{await probe('/api/v1/settings','PUT',{drop:true});await c.evaluate("const el=document.querySelector('#header-language');el.value='en';el.dispatchEvent(new Event('change',{bubbles:true}));return true;");await c.waitFor('window.__localeHeld',10000);assert(await c.evaluate("return document.documentElement.lang==='uk'"),'Unconfirmed locale applied');await release();await c.waitFor("document.documentElement.lang==='en' && !document.querySelector('#header-language').disabled",10000);const calls=await c.evaluate('return window.__localeRequests');assert(calls.length===1&&calls[0].status===200,'Lost ACK replayed or did not commit');await restore();});
    await check('I18NB3 real cross-tab settings CAS adopts the authoritative winner',async()=>{const before=await api(peer,'/api/v1/settings');const changed=await api(peer,'/api/v1/settings','PUT',{expectedRevision:before.data.revision,settings:{language:'tr'}});assert(changed.status===200,'Peer settings update failed');await probe('/api/v1/settings','PUT');await c.evaluate("const el=document.querySelector('#header-language');el.value='ar';el.dispatchEvent(new Event('change',{bubbles:true}));return true;");await c.waitFor('window.__localeHeld',10000);await release();await c.waitFor("document.documentElement.lang==='tr' && !document.querySelector('#header-language').disabled",10000);const calls=await c.evaluate('return window.__localeRequests');assert(calls.length===1&&calls[0].status===409,'Stale update was not one actual CAS conflict');await restore();});
    await check('I18NB4 dirty draft, caret and synthetic composition survive label updates and held save',async()=>{attempt=await draft();await probe('/api/v1/attempts/'+attempt.id,'PUT');await c.evaluate(`window.__editor=document.querySelector('#writing-text');window.__editor.focus();window.__editor.value=${JSON.stringify(text)};window.__editor.setSelectionRange(12,19);window.__editor.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:'synthetic'}));window.__editor.dispatchEvent(new InputEvent('input',{bubbles:true,data:'synthetic',isComposing:true}));return true;`);await locale('ar');assert(await c.evaluate(`return document.querySelector('#writing-text')===window.__editor && window.__editor.value===${JSON.stringify(text)} && window.__editor.selectionStart===12 && window.__editor.selectionEnd===19;`),'Locale replaced dirty editor or caret');await c.evaluate("window.__editor.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));window.__editor.dispatchEvent(new Event('input',{bubbles:true}));return true;");await c.waitFor('window.__localeHeld',10000);await locale('en');assert(await c.evaluate('return document.querySelector("#writing-text")===window.__editor && window.__editor.selectionStart===12'),'Held save locale update replaced editor');await directions('en');const prompt=await c.evaluate("return {situation:document.querySelector('.writing-prompt > p[lang]').textContent,points:[...document.querySelectorAll('.writing-prompt .leitpunkte li')].map(n=>n.textContent),lang:document.querySelector('.writing-prompt .leitpunkte').lang,dir:document.querySelector('.writing-prompt .leitpunkte').dir,editorLang:document.querySelector('#writing-text').lang};");assert(prompt.situation===fixture.writingTasks[0].situation&&JSON.stringify(prompt.points)===JSON.stringify(fixture.writingTasks[0].leitpunkte)&&prompt.lang==='de'&&prompt.dir==='ltr'&&prompt.editorLang==='de','German writing scenario/Leitpunkte changed or mistagged');await release();await c.waitFor("!document.querySelector('#writing-submit').disabled",10000);assert((await api(c,'/api/v1/attempts/'+attempt.id)).data.text===text,'Real save lost draft');assert((await c.evaluate('return window.__localeRequests')).length===1,'Locale produced extra draft writes');await restore();});
    await check('I18NB5 real stub assessment and original submission remain immutable under locale selection',async()=>{await clickSel(c,'#writing-submit');await c.waitFor("document.querySelector('#writing-state').dataset.submissionId",15000);submission=await c.evaluate("return document.querySelector('#writing-state').dataset.submissionId");drainWorker();await c.waitFor("document.querySelector('.criteria .criterion')",20000);const saved=await api(c,'/api/v1/submissions/'+submission);assert(saved.data.assessment&&saved.data.submission.text===text&&saved.data.submission.explanation_language==='en','Confirmed submission snapshot incorrect');gradedFacts=await graded();for(const language of locales){await locale(language);assert(await graded()===gradedFacts,'Locale mutated grading, job, credit or usage facts');await layout('i18n-result-'+language,'#history-detail');}});
    await check('I18NB6 all five locales render dashboard, navigation, account, practice, history and checkout at three widths',async()=>{for(const language of locales){await locale(language);for(const [name,route,selector] of [['dashboard','heute','#view-heute'],['navigation','mehr','#view-mehr'],['account','einstellungen','#view-einstellungen'],['practice','schreiben','#view-schreiben'],['history','fortschritt','#view-fortschritt'],['checkout','checkout','#checkout-host']]){await page('#/prep/'+prep.id+'/'+route);await c.waitFor(`document.querySelector(${JSON.stringify(selector)}) && !document.querySelector(${JSON.stringify(selector)}).closest('.view').hidden`,10000);if(name==='checkout'){await c.waitFor("document.querySelector('#checkout-market')",10000);await setInputs(c,{'checkout-market':'DE'});await c.waitFor("['existing','ready'].includes(document.querySelector('#checkout-host').dataset.state)",10000);}assert(await c.evaluate(`return document.documentElement.lang===${JSON.stringify(language)} && document.documentElement.dir===${JSON.stringify(language==='ar'?'rtl':'ltr')}`),'Wrong document locale/direction');const labels=await c.evaluate("return (async()=>{const {t}=await import('/assets/i18n/core.js');const rows=[...document.querySelectorAll('[data-i18n]')].filter(n=>!n.children.length&&n.getBoundingClientRect().height);return {count:rows.length,bad:rows.filter(n=>n.textContent!==t(n.dataset.i18n)).map(n=>n.dataset.i18n)};})()");assert(labels.count>4&&!labels.bad.length,'Visible locale bindings are stale '+JSON.stringify(labels));if(name==='dashboard')assert(await c.evaluate("return (async()=>{const {t}=await import('/assets/i18n/core.js');return document.querySelector('#stat-answers').nextElementSibling.textContent===t('shell.m320');})()"),'Answered counter label is not localized');if(name==='practice'){await c.waitFor("document.querySelector('#view-schreiben .chip')",10000);assert(await c.evaluate("return (async()=>{const {t}=await import('/assets/i18n/core.js');const chips=[...document.querySelectorAll('#view-schreiben .chip')];return chips.length>0&&chips.every(node=>node.textContent===t('shell.m005'));})()"),'Writing family badges are not localized');}await layout('i18n-'+language+'-'+name,selector);}}assert(await graded()===gradedFacts,'Browsing translated surfaces changed grading facts');});
    await check('I18NB7 selected answer and pending real save retain control and event identity',async()=>{await page('#/prep/'+prep.id+'/abschnitt');await c.waitFor("document.querySelector('[data-mock-start]')",10000);await pointer('[data-mock-start]');await c.waitFor("document.querySelector('.mock-options input')",12000);const id=await c.evaluate("return location.hash.split('/').at(-1)");run=(await api(c,'/api/v1/mock-runs/'+id)).data;assert(run.timing?.active_group_id&&run.deadline_at,'Authoritative timed mock absent');await probe('/api/v1/mock-runs/'+id,'PUT');await pointer('.mock-options input');await clickSel(c,'[data-mock-action=save]');await c.waitFor('window.__localeHeld',10000);await c.evaluate("window.__answer=document.querySelector('.mock-options input:checked');window.__originalOptions=document.querySelector('.mock-options').textContent;return true;");await locale('uk');assert(await c.evaluate("return document.querySelector('.mock-options input:checked')===window.__answer && window.__answer.checked && document.querySelector('.mock-options').textContent===window.__originalOptions && document.querySelector('.mock-options').lang==='de' && document.querySelector('.mock-options').dir==='ltr'"),'Locale replaced pending selected answer');await directions('uk');await release();await c.waitFor("!document.querySelector('[data-mock-action=save]').disabled",10000);const calls=await c.evaluate('return window.__localeRequests');assert(calls.length===1&&calls[0].status===200&&calls[0].body.eventId,'Pending save event not preserved');const saved=(await api(c,'/api/v1/mock-runs/'+id)).data;assert(saved.responses.length===1&&saved.deadline_at===run.deadline_at&&JSON.stringify(saved.timing.groups.map(x=>[x.starts_at,x.deadline_at]))===JSON.stringify(run.timing.groups.map(x=>[x.starts_at,x.deadline_at])),'Locale reset timer or saved response');run=saved;await restore();});
    await check('I18NB8 active native audio survives five locale switches without another play allowance',async()=>{await pointer('[data-listening-action=load]');await c.waitFor("document.querySelector('[data-listening-action=play]') && !document.querySelector('[data-listening-action=play]').disabled",10000);await pointer('[data-listening-action=play]');await c.waitFor("!document.querySelector('[data-listening-audio]').paused && document.querySelector('[data-listening-audio]').currentTime>0.2",12000);await c.evaluate("window.__audio=document.querySelector('[data-listening-audio]');window.__position=window.__audio.currentTime;return true;");const before=(await api(c,'/api/v1/mock-runs/'+run.id+'/playback')).data.items;assert(before[0].plays_used===1,'No real begin receipt');for(const language of locales){await locale(language);assert(await c.evaluate("return document.querySelector('[data-listening-audio]')===window.__audio && !window.__audio.paused && window.__audio.currentTime>=window.__position && !window.__audio.ended"),'Locale replaced, paused or rewound native audio');await directions(language);await shot(c,'i18n-audio-'+language,'.listening-player');}const after=(await api(c,'/api/v1/mock-runs/'+run.id+'/playback')).data.items;assert(after[0].plays_used===1&&after[0].playback_id===before[0].playback_id,'Locale consumed another play or rotated receipt');await pointer('[data-listening-action=pause]');await c.waitFor("document.querySelector('[data-listening-audio]').paused",10000);});
    await check('I18NB9 held and lost finalise ACK retries the exact original event and language snapshot',async()=>{await locale('uk');await probe('/api/v1/mock-runs/'+run.id+'/finalise','POST',{drop:true});await clickSel(c,'[data-mock-action=confirm]');await clickSel(c,'[data-mock-action=finalise]');await c.waitFor('window.__localeHeld',12000);const saved=(await api(c,'/api/v1/mock-runs/'+run.id)).data;assert(saved.state==='finalised','Held response did not actually finalise');await locale('ar');await release();await c.waitFor("document.querySelector('[data-mock-action=retry]')",10000);await clickSel(c,'[data-mock-action=retry]');await c.waitFor("document.querySelector('#mock-result')",12000);const calls=await c.evaluate('return window.__localeRequests');assert(calls.length===2&&calls.every(x=>x.status===200)&&JSON.stringify(calls[0].body)===JSON.stringify(calls[1].body)&&calls[0].body.explanationLanguage==='uk','Finalise retry lost original identity/language');assert((await api(c,'/api/v1/mock-runs/'+run.id)).data.revision===saved.revision,'Retry finalised twice');assert(await graded()===gradedFacts,'Empty writing finalise or locale changed prior grading facts');await restore();await layout('i18n-finalised-ar','#mock-result');});
    await check('I18NB10 actual signup stores its selected language before account bootstrap',async()=>{const signup=await launch();await navigate(signup,base+'/signin');await setInputs(signup,{'interface-language':'tr'});await clickSel(signup,'#tab-signup');await setInputs(signup,{'su-name':'Synthetic Locale','su-email':'locale-'+randomUUID()+'@example.test','su-password':password});await clickSel(signup,'#su-submit');await boot(signup);const settings=await api(signup,'/api/v1/settings');assert(settings.data.settings.language==='tr'&&await signup.evaluate("return document.documentElement.lang==='tr'"),'Signup lost selected language');await shot(signup,'i18n-signup-tr-desktop');});
    await check('I18NB11 account switch preserves recovery text and fences a late settings acknowledgement',async()=>{
      await page('#/prep/'+prep.id+'/heute');await locale('de');
      const recoveryAttempt=await draft(),recoveryText='Synthetische lokale Kopie nach einem Kontowechsel. Dieser Text muss kopierbar bleiben.';
      const confirmed=(await api(c,'/api/v1/settings')).data;
      await probe('/api/v1/settings','PUT');
      await c.evaluate("window.__terminalReasons=[];addEventListener('hatoove:session-expired',event=>window.__terminalReasons.push(event.detail?.reason));const el=document.querySelector('#header-language');el.value='uk';el.dispatchEvent(new Event('change',{bubbles:true}));return true;");
      await c.waitFor('window.__localeHeld',10000);
      // The old owner's PUT really committed. Keep only its response pending while changing real cookies.
      assert((await api(peer,'/api/v1/settings')).data.settings.language==='uk','Held old-account preference did not commit');
      const switchResult=await c.evaluate(`return (async()=>{const native=window.__localeNative;await native('/api/auth/sign-out',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const response=await native('/api/auth/sign-in/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:${JSON.stringify(newcomerEmail)},password:${JSON.stringify(password)}})});if(response.status!==200)return response.status;window.__recoveryEditor=document.querySelector('#writing-text');window.__recoveryEditor.value=${JSON.stringify(recoveryText)};window.__recoveryEditor.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:'synthetic'}));window.dispatchEvent(new Event('focus'));return response.status;})()`);
      assert(switchResult===200,'Actual cookie account switch failed');
      await c.waitFor("window.__terminalReasons.includes('account_changed') && !document.querySelector('#error').hidden && document.querySelector('#writing-text').readOnly",12000);
      await release();
      // Let the actual API promise process the released stale response before inspecting the locale.
      await c.evaluate("return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(true))));");
      const terminal=await c.evaluate(`return (async()=>{const {t,getLocale}=await import('/assets/i18n/core.js');const {api}=await import('/app/api.js');const before=window.__localeAllRequests.length;const settings=await api.settings.write(${confirmed.revision},{language:'ar'});const draft=await api.writing.saveDraft(${JSON.stringify(recoveryAttempt.id)},0,${JSON.stringify(recoveryText)});return {notice:document.querySelector('#error').textContent.includes(t('shell.m017'))&&document.querySelector('#error').textContent.includes(t('shell.m019')),locale:getLocale(),lang:document.documentElement.lang,headerDisabled:document.querySelector('#header-language').disabled,sameEditor:document.querySelector('#writing-text')===window.__recoveryEditor,text:window.__recoveryEditor.value,readonly:window.__recoveryEditor.readOnly,disabled:window.__recoveryEditor.disabled,submitDisabled:document.querySelector('#writing-submit').disabled,settings,draft,extraRequests:window.__localeAllRequests.length-before,calls:window.__localeRequests.length};})()`);
      assert(terminal.notice&&terminal.locale==='de'&&terminal.lang==='de'&&terminal.headerDisabled,'Late old-account ACK changed confirmed locale or terminal notice');
      assert(terminal.sameEditor&&terminal.text===recoveryText&&terminal.readonly&&!terminal.disabled&&terminal.submitDisabled,'Account change destroyed or unlocked the local recovery copy');
      assert([terminal.settings,terminal.draft].every(row=>row.status===409&&row.error==='account_changed')&&terminal.extraRequests===0&&terminal.calls===1,'Terminal API allowed writes or replayed the settings event');
      assert((await api(peer,'/api/v1/attempts/'+recoveryAttempt.id)).data.text==='','Local copy was persisted under changed cookies');
      assert((await api(c,'/api/v1/settings')).data.settings.language==='de','Old account preference crossed into the new account');
      await shot(c,'i18n-account-changed-recovery','#writing-text');await shot(c,'i18n-account-changed-notice','#error');
      // Keep the readonly recovery window intact; do not dismiss its legitimate beforeunload warning.
      await restore();c=await launch();await signin(c,newcomerEmail);
      assert((await api(c,'/api/v1/settings')).data.settings.language==='de','Fresh account boot inherited the old account language');
    });
    await check('I18NB12 Back navigation revalidates server preference; BFCache use is reported explicitly',async()=>{await signin(c,email);await page('#/prep/'+prep.id+'/heute');await locale('en');await c.evaluate("window.__restored=false;addEventListener('pageshow',event=>{window.__restored=event.persisted;});return true;");await navigate(c,base+'/');const settings=await api(peer,'/api/v1/settings');assert((await api(peer,'/api/v1/settings','PUT',{expectedRevision:settings.data.revision,settings:{language:'ar'}})).status===200,'Peer preference update failed');await c.send('Page.getNavigationHistory').then(async history=>{const previous=history.entries[history.currentIndex-1];assert(previous?.url.includes('/app/'),'Back target not the owned app');await c.send('Page.navigateToHistoryEntry',{entryId:previous.id});});await ready(c);await c.waitFor("document.documentElement.lang==='ar'",12000);const restored=await c.evaluate('return window.__restored===true');return 'Actual Back restore passed; pageshow.persisted='+restored+' (false does not prove BFCache).';});
    await check('I18NB13 no uncaught exceptions, external browser calls or payment session',async()=>{const errors=connections.flatMap(client=>client.events.filter(event=>event.method==='Runtime.exceptionThrown'));assert(!errors.length,JSON.stringify(errors.slice(0,3)));const requests=connections.flatMap(client=>client.events.filter(event=>event.method==='Network.requestWillBeSent').map(event=>event.params.request.url));assert(requests.length>0,'Network observation absent');assert(!requests.some(value=>/^https?:/.test(value)&&new URL(value).origin!==base),'External browser request');assert(!requests.some(value=>new URL(value,base).pathname==='/api/v1/checkout/session'),'Unexpected checkout session');});
  } finally {
    for(const client of connections)try{client.ws.close();}catch(error){record('I18N CDP cleanup',false,error.message);}
    for(const browser of browsers){try{await browser.cleanup();assert(!fs.existsSync(browser.profile),'Disposable browser profile remains');assert(browser.proc.exitCode!==null||browser.proc.signalCode!==null,'Disposable browser process remains');record('I18N browser cleanup',true,JSON.stringify({pid:browser.proc.pid,profile:browser.profile}));}catch(error){record('I18N browser cleanup',false,error.message);}}
  }
}
